/**
 * Column Mapping Dialog
 * ======================
 * Clean, user-friendly column mapping interface. The user always sees this
 * step after selecting a CSV — they pick which of THEIR columns corresponds
 * to each field the system needs. No auto-detection, no internal column names
 * exposed. Just 4 simple fields:
 *
 *   1. Título de la opinión (optional)
 *   2. Texto de la opinión (required)
 *   3. Fecha de la opinión (optional — temporal analysis unavailable without it)
 *   4. Calificación / Polaridad (optional — auto-generated by sentiment model if missing)
 */

import React, { useCallback, useMemo, useState } from 'react';
import {
  ArrowRight,
  Check,
  AlertTriangle,
  Info,
  X,
  FileSpreadsheet,
  Loader2,
  Eye,
  EyeOff,
  MessageSquareText,
  Calendar,
  Star,
  Type,
} from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { Button } from './ui';
import { cn } from '../lib/utils';
import type { ColumnMapping } from '../../shared/types';

/* ------------------------------------------------------------------ */
/*  Field definitions — what the USER sees (not internal column names) */
/* ------------------------------------------------------------------ */

interface MappingField {
  /** Internal system column name (hidden from user) */
  systemName: string;
  /** Translation key for user-facing label */
  labelKey: string;
  /** Translation key for short helper text */
  descriptionKey: string;
  /** Is this field required? */
  required: boolean;
  /** Icon component */
  icon: React.ElementType;
}

const MAPPING_FIELDS: MappingField[] = [
  {
    systemName: 'Titulo',
    labelKey: 'columnMapping.fields.titleLabel',
    descriptionKey: 'columnMapping.fields.titleDesc',
    required: false,
    icon: Type,
  },
  {
    systemName: 'Review',
    labelKey: 'columnMapping.fields.textLabel',
    descriptionKey: 'columnMapping.fields.textDesc',
    required: true,
    icon: MessageSquareText,
  },
  {
    systemName: 'FechaEstadia',
    labelKey: 'columnMapping.fields.dateLabel',
    descriptionKey: 'columnMapping.fields.dateDesc',
    required: false,
    icon: Calendar,
  },
  {
    systemName: 'Calificacion',
    labelKey: 'columnMapping.fields.ratingLabel',
    descriptionKey: 'columnMapping.fields.ratingDesc',
    required: false,
    icon: Star,
  },
];

/* ------------------------------------------------------------------ */
/*  Props                                                              */
/* ------------------------------------------------------------------ */

interface ColumnMappingDialogProps {
  /** The name of the file the user selected */
  fileName: string;
  /** Columns found in the user's CSV file */
  sourceColumns: string[];
  /** Number of rows in the source file */
  rowCount: number;
  /** First rows of the source data for preview */
  previewData?: Record<string, unknown>[];
  /** Whether the mapping is being applied */
  isApplying: boolean;
  /** Called when user confirms the mapping */
  onApply: (mapping: ColumnMapping) => void;
  /** Called when user cancels */
  onCancel: () => void;
}

/* ------------------------------------------------------------------ */
/*  Component                                                          */
/* ------------------------------------------------------------------ */

export function ColumnMappingDialog({
  fileName,
  sourceColumns,
  rowCount,
  previewData,
  isApplying,
  onApply,
  onCancel,
}: ColumnMappingDialogProps) {
  const { t } = useTranslation('components');
  // All fields start blank — user must explicitly choose
  const [selections, setSelections] = useState<Record<string, string | null>>(
    () => {
      const init: Record<string, string | null> = {};
      for (const f of MAPPING_FIELDS) {
        init[f.systemName] = null;
      }
      return init;
    }
  );

  const [showPreview, setShowPreview] = useState(false);

  /* ---- handlers ---- */

  const handleChange = useCallback(
    (systemName: string, value: string | null) => {
      setSelections((prev) => ({ ...prev, [systemName]: value }));
    },
    []
  );

  const handleApply = useCallback(() => {
    // Build the ColumnMapping the backend expects
    const mapping: ColumnMapping = {};
    for (const f of MAPPING_FIELDS) {
      mapping[f.systemName] = selections[f.systemName] || null;
    }
    onApply(mapping);
  }, [selections, onApply]);

  /* ---- derived state ---- */

  // Which source columns are already used?
  const usedColumns = useMemo(
    () => new Set(Object.values(selections).filter(Boolean) as string[]),
    [selections]
  );

  // Validation
  const validation = useMemo(() => {
    const missing: string[] = [];
    let assignedCount = 0;

    for (const f of MAPPING_FIELDS) {
      if (selections[f.systemName]) {
        assignedCount++;
      } else if (f.required) {
        missing.push(f.labelKey);
      }
    }

    return {
      isValid: missing.length === 0,
      missing,
      assignedCount,
      total: MAPPING_FIELDS.length,
    };
  }, [selections]);

  /* ---- render ---- */

  return (
    <div className="bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 overflow-hidden shadow-sm">
      {/* ============= Header ============= */}
      <div className="flex items-center justify-between p-5 border-b border-slate-200 dark:border-slate-700">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-lg bg-blue-100 dark:bg-blue-900/40 flex items-center justify-center">
            <FileSpreadsheet className="w-5 h-5 text-blue-600 dark:text-blue-400" />
          </div>
          <div>
            <h3 className="font-semibold text-slate-900 dark:text-white">
              {t('columnMapping.title')}
            </h3>
            <p className="text-sm text-slate-500 dark:text-slate-400">
              <span className="font-medium text-slate-700 dark:text-slate-300">
                {fileName}
              </span>{' '}
              — {rowCount.toLocaleString()} filas, {sourceColumns.length} columnas
            </p>
          </div>
        </div>
        <button
          onClick={onCancel}
          className="p-2 rounded-lg hover:bg-slate-200 dark:hover:bg-slate-700 transition-colors"
          title="Cancelar"
        >
          <X className="w-5 h-5 text-slate-500 dark:text-slate-400" />
        </button>
      </div>

      {/* ============= Info ============= */}
      <div className="mx-5 mt-5 p-3 bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg flex items-start gap-2.5">
        <Info className="w-4 h-4 text-blue-600 dark:text-blue-400 mt-0.5 shrink-0" />
        <p className="text-sm text-blue-700 dark:text-blue-300">
          {t('columnMapping.info')}
        </p>
      </div>

      {/* ============= Mapping Fields ============= */}
      <div className="p-5 space-y-3">
        {MAPPING_FIELDS.map((field) => {
          const current = selections[field.systemName];
          const isMapped = !!current;
          const isMissing = field.required && !isMapped;
          const IconComp = field.icon;

          return (
            <div
              key={field.systemName}
              className={cn(
                'flex items-center gap-4 p-4 rounded-lg border transition-colors',
                isMapped
                  ? 'border-green-200 dark:border-green-800 bg-green-50/50 dark:bg-green-900/10'
                  : isMissing
                    ? 'border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800'
                    : 'border-slate-200 dark:border-slate-700 bg-slate-50/50 dark:bg-slate-800/50'
              )}
            >
              {/* Left: icon + label */}
              <div className="flex items-start gap-3 flex-1 min-w-0">
                <div
                  className={cn(
                    'w-9 h-9 rounded-lg flex items-center justify-center shrink-0 mt-0.5',
                    isMapped
                      ? 'bg-green-100 dark:bg-green-900/30'
                      : 'bg-slate-100 dark:bg-slate-700'
                  )}
                >
                  <IconComp
                    className={cn(
                      'w-4.5 h-4.5',
                      isMapped
                        ? 'text-green-600 dark:text-green-400'
                        : 'text-slate-500 dark:text-slate-400'
                    )}
                  />
                </div>
                <div className="min-w-0">
                  <div className="flex items-center gap-2">
                    <span className="font-medium text-sm text-slate-900 dark:text-white">
                      {t(field.labelKey)}
                    </span>
                    {field.required ? (
                      <span className="text-[10px] px-1.5 py-0.5 rounded bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-400 font-semibold uppercase tracking-wide">
                        {t('columnMapping.required')}
                      </span>
                    ) : (
                      <span className="text-[10px] px-1.5 py-0.5 rounded bg-slate-100 dark:bg-slate-700 text-slate-500 dark:text-slate-400 font-medium">
                        {t('columnMapping.optional')}
                      </span>
                    )}
                  </div>
                  <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5 leading-relaxed">
                    {t(field.descriptionKey)}
                  </p>
                </div>
              </div>

              {/* Arrow */}
              <ArrowRight className="w-4 h-4 text-slate-300 dark:text-slate-600 shrink-0" />

              {/* Right: dropdown */}
              <div className="w-56 shrink-0">
                <select
                  value={current || ''}
                  onChange={(e) =>
                    handleChange(field.systemName, e.target.value || null)
                  }
                  className={cn(
                    'w-full rounded-md border px-3 py-2 text-sm transition-colors',
                    'bg-white dark:bg-slate-900',
                    'focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500',
                    isMapped
                      ? 'border-green-300 dark:border-green-700 text-slate-900 dark:text-slate-100'
                      : 'border-slate-300 dark:border-slate-600 text-slate-500 dark:text-slate-400'
                  )}
                >
                  <option value="">{t('columnMapping.selectColumn')}</option>
                  {sourceColumns.map((col) => {
                    const usedElsewhere =
                      usedColumns.has(col) && col !== current;
                    return (
                      <option
                        key={col}
                        value={col}
                        disabled={usedElsewhere}
                      >
                        {col}
                        {usedElsewhere ? t('columnMapping.alreadyAssigned') : ''}
                      </option>
                    );
                  })}
                </select>
              </div>

              {/* Status */}
              <div className="w-6 shrink-0 flex justify-center">
                {isMapped ? (
                  <Check className="w-5 h-5 text-green-500" />
                ) : isMissing ? (
                  <AlertTriangle className="w-4 h-4 text-amber-400" />
                ) : (
                  <div className="w-5" />
                )}
              </div>
            </div>
          );
        })}
      </div>

      {/* ============= Source Preview ============= */}
      {previewData && previewData.length > 0 && (
        <div className="px-5 pb-3">
          <button
            onClick={() => setShowPreview((v) => !v)}
            className="flex items-center gap-1.5 text-sm text-blue-600 dark:text-blue-400 hover:text-blue-700 dark:hover:text-blue-300 transition-colors"
          >
            {showPreview ? (
              <EyeOff className="w-3.5 h-3.5" />
            ) : (
              <Eye className="w-3.5 h-3.5" />
            )}
            {showPreview
              ? t('columnMapping.hidePreview')
              : t('columnMapping.showPreview')}
          </button>
          {showPreview && (
            <div className="mt-2 overflow-x-auto border border-slate-200 dark:border-slate-700 rounded-lg">
              <table className="w-full text-xs">
                <thead>
                  <tr className="bg-slate-50 dark:bg-slate-900 border-b border-slate-200 dark:border-slate-700">
                    {Object.keys(previewData[0]).map((key) => (
                      <th
                        key={key}
                        className="text-left p-2 font-medium text-slate-600 dark:text-slate-400 whitespace-nowrap"
                      >
                        {key}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {previewData.slice(0, 5).map((row, i) => (
                    <tr
                      key={i}
                      className="border-b border-slate-100 dark:border-slate-800 last:border-0"
                    >
                      {Object.values(row).map((value, j) => (
                        <td
                          key={j}
                          className="p-2 text-slate-700 dark:text-slate-300 max-w-50 truncate whitespace-nowrap"
                        >
                          {value == null ? (
                            <span className="text-slate-400 dark:text-slate-500 italic">—</span>
                          ) : (
                            String(value)
                          )}
                        </td>
                      ))}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      )}

      {/* ============= Validation Warning ============= */}
      {!validation.isValid && (
        <div className="mx-5 mb-3 p-3 bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800 rounded-lg flex items-start gap-2.5">
          <AlertTriangle className="w-4 h-4 text-amber-500 mt-0.5 shrink-0" />
          <p className="text-sm text-amber-700 dark:text-amber-300">
            {t('columnMapping.missingRequired')}
            <strong>{validation.missing.map(k => t(k)).join(', ')}</strong>
          </p>
        </div>
      )}

      {/* ============= Footer ============= */}
      <div className="flex items-center justify-between gap-3 p-4 border-t border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-900/50">
        <span className="text-xs text-slate-500 dark:text-slate-400">
          {t('columnMapping.fieldsAssigned', { assigned: validation.assignedCount, total: validation.total })}
        </span>
        <div className="flex items-center gap-3">
          <Button variant="outline" onClick={onCancel} disabled={isApplying}>
            {t('columnMapping.cancel')}
          </Button>
          <Button
            onClick={handleApply}
            disabled={!validation.isValid || isApplying}
          >
            {isApplying ? (
              <>
                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                {t('columnMapping.processing')}
              </>
            ) : (
              <>
                <Check className="w-4 h-4 mr-2" />
                {t('columnMapping.loadDataset')}
              </>
            )}
          </Button>
        </div>
      </div>
    </div>
  );
}
