/**
 * Insights Page
 * ==============
 * Professional display of textual analysis insights:
 * - KPI cards (total opinions, sentiment %, avg rating, etc.)
 * - Fortalezas & Debilidades ranking tables
 * - LLM-generated summaries (descriptivo, estructurado, insights)
 *   with global overview + per-category tabs
 *
 * Data source: insights_textuales.json (generated by Phase 07)
 */

import React, { useState, useEffect, useCallback, useMemo } from 'react';
import ReactMarkdown from 'react-markdown';
import {
  Lightbulb,
  RefreshCw,
  Star,
  ThumbsUp,
  ThumbsDown,
  BarChart3,
  FileText,
  Target,
  Award,
  AlertTriangle,
  Copy,
  Check,
  Download,
  Info,
  Folder,
  Globe,
  Tag,
  Database,
  Hash,
  MessageSquare,
  Calendar,
  TrendingUp,
  type LucideIcon,
} from 'lucide-react';
import { PageLayout } from '../components/layout';
import { Button } from '../components/ui';
import { cn } from '../lib/utils';

/* ──────────────────── Types ──────────────────── */

interface InsightsKpis {
  total_opiniones: number;
  porcentaje_positivo: number;
  porcentaje_neutro: number;
  porcentaje_negativo: number;
  calificacion_promedio: number;
  mejor_categoria: string;
  peor_categoria: string;
  subtopico_mas_mencionado: string;
}

interface FortalezaItem {
  categoria: string;
  porcentaje_positivo: number;
  total_menciones: number;
}

interface DebilidadItem {
  categoria: string;
  porcentaje_negativo: number;
  total_menciones: number;
}

interface ValidacionDataset {
  total_opiniones: number;
  tiene_fechas: boolean;
  rango_temporal_dias: number;
  categorias_identificadas: number;
  tiene_topicos: boolean;
  subtopicos_detectados: number;
  sentimientos: { positivo: number; neutro: number; negativo: number };
  recomendaciones: string[];
}

interface ResumenesData {
  descriptivo?: {
    por_categoria?: Record<string, string>;
    global?: string;
  };
  estructurado?: {
    por_categoria?: Record<string, string>;
    global?: string;
  };
  insights?: {
    por_categoria?: Record<string, string>;
    global?: string;
  };
}

interface DistributionItem {
  cantidad: number;
  porcentaje: number;
}

interface TopicItem {
  nombre: string;
  cantidad: number;
  porcentaje: number;
}

interface EstadisticasDataset {
  total_registros: number;
  sentimiento: Record<string, DistributionItem> | null;
  subjetividad: Record<string, DistributionItem> | null;
  calificacion: Record<string, DistributionItem> | null;
  calificacion_promedio?: number;
  calificacion_mediana?: number;
  categorias: Record<string, DistributionItem> | null;
  categorias_meta?: {
    total_asignaciones: number;
    promedio_categorias_por_review: number;
    categorias_unicas: number;
  };
  topicos: TopicItem[] | null;
  temporal: {
    fecha_min: string;
    fecha_max: string;
    rango_dias: number;
    registros_con_fecha: number;
    registros_sin_fecha: number;
  } | null;
  longitud_texto: {
    promedio: number;
    mediana: number;
    minimo: number;
    maximo: number;
  } | null;
}

interface InsightsData {
  fecha_generacion: string;
  validacion_dataset: ValidacionDataset;
  kpis: InsightsKpis;
  fortalezas: FortalezaItem[];
  debilidades: DebilidadItem[];
  resumenes: ResumenesData;
  estadisticas_dataset?: EstadisticasDataset;
}

/* ──────────────────── Sub-components ──────────────────── */

function KpiCard({
  label,
  value,
  icon: Icon,
  color,
  subtitle,
}: {
  label: string;
  value: string | number;
  icon: React.ComponentType<{ className?: string }>;
  color: string;
  subtitle?: string;
}) {
  return (
    <div className="bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 p-4 flex items-start gap-3">
      <div className={cn('p-2 rounded-lg', color)}>
        <Icon className="w-5 h-5 text-white" />
      </div>
      <div className="min-w-0 flex-1">
        <p className="text-xs font-medium text-slate-500 dark:text-slate-400 uppercase tracking-wide">
          {label}
        </p>
        <p className="text-xl font-bold text-slate-900 dark:text-white mt-0.5 truncate">
          {value}
        </p>
        {subtitle && (
          <p className="text-xs text-slate-400 dark:text-slate-500 mt-0.5 truncate">
            {subtitle}
          </p>
        )}
      </div>
    </div>
  );
}

function SentimentBar({
  positive,
  neutral,
  negative,
}: {
  positive: number;
  neutral: number;
  negative: number;
}) {
  return (
    <div className="w-full">
      <div className="flex h-3 rounded-full overflow-hidden bg-slate-100 dark:bg-slate-700">
        <div
          className="bg-green-500 transition-all"
          style={{ width: `${positive}%` }}
          title={`Positivo: ${positive}%`}
        />
        <div
          className="bg-slate-400 transition-all"
          style={{ width: `${neutral}%` }}
          title={`Neutro: ${neutral}%`}
        />
        <div
          className="bg-red-500 transition-all"
          style={{ width: `${negative}%` }}
          title={`Negativo: ${negative}%`}
        />
      </div>
      <div className="flex justify-between mt-1.5 text-xs text-slate-500 dark:text-slate-400">
        <span className="flex items-center gap-1">
          <span className="w-2 h-2 rounded-full bg-green-500" />
          Positivo {positive}%
        </span>
        <span className="flex items-center gap-1">
          <span className="w-2 h-2 rounded-full bg-slate-400" />
          Neutro {neutral}%
        </span>
        <span className="flex items-center gap-1">
          <span className="w-2 h-2 rounded-full bg-red-500" />
          Negativo {negative}%
        </span>
      </div>
    </div>
  );
}

function RankingTable({
  title,
  icon: Icon,
  items,
  valueKey,
  valueColor,
}: {
  title: string;
  icon: React.ComponentType<{ className?: string }>;
  items: FortalezaItem[] | DebilidadItem[];
  valueKey: string;
  valueColor: string;
}) {
  return (
    <div className="bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 overflow-hidden">
      <div className="px-4 py-3 border-b border-slate-200 dark:border-slate-700 flex items-center gap-2">
        <Icon className={cn('w-5 h-5', valueColor)} />
        <h3 className="font-semibold text-slate-900 dark:text-white text-sm">{title}</h3>
      </div>
      <div className="divide-y divide-slate-100 dark:divide-slate-700/50">
        {items.slice(0, 8).map((item, idx) => (
          <div key={item.categoria} className="flex items-center px-4 py-2.5 gap-3">
            <span
              className={cn(
                'w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold',
                idx < 3
                  ? `${valueColor.replace('text-', 'bg-').replace('500', '100')} ${valueColor}`
                  : 'bg-slate-100 dark:bg-slate-700 text-slate-500 dark:text-slate-400'
              )}
            >
              {idx + 1}
            </span>
            <span className="flex-1 text-sm text-slate-700 dark:text-slate-300 truncate">
              {item.categoria}
            </span>
            <span className={cn('text-sm font-semibold', valueColor)}>
              {Number((item as unknown as Record<string, number>)[valueKey]).toFixed(1)}%
            </span>
            <span className="text-xs text-slate-400 dark:text-slate-500 w-16 text-right">
              {item.total_menciones} ops
            </span>
          </div>
        ))}
        {items.length === 0 && (
          <p className="px-4 py-6 text-sm text-slate-400 text-center">Sin datos</p>
        )}
      </div>
    </div>
  );
}

/* ──────────────────── Summary Section (tabs) ──────────────────── */

type SummaryType = 'descriptivo' | 'estructurado' | 'insights';

const SUMMARY_TABS: { id: SummaryType; label: string; icon: React.ComponentType<{ className?: string }> }[] = [
  { id: 'descriptivo', label: 'Resumen Descriptivo', icon: FileText },
  { id: 'estructurado', label: 'Resumen Estructurado', icon: Target },
  { id: 'insights', label: 'Insights Estratégicos', icon: Lightbulb },
];

function SummarySection({ resumenes }: { resumenes: ResumenesData }) {
  const [activeTab, setActiveTab] = useState<SummaryType>('descriptivo');
  const [activeCategory, setActiveCategory] = useState<string>('global');
  const [copiedId, setCopiedId] = useState<string | null>(null);

  const currentSummary = resumenes[activeTab];
  const categories = useMemo(() => {
    if (!currentSummary?.por_categoria) return [];
    return Object.keys(currentSummary.por_categoria).sort();
  }, [currentSummary]);

  const currentContent = useMemo(() => {
    if (!currentSummary) return null;
    if (activeCategory === 'global') return currentSummary.global || null;
    return currentSummary.por_categoria?.[activeCategory] || null;
  }, [currentSummary, activeCategory]);

  // Reset category when switching tabs
  useEffect(() => {
    setActiveCategory('global');
  }, [activeTab]);

  const handleCopy = async (text: string, id: string) => {
    await navigator.clipboard.writeText(text);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  if (!resumenes || Object.keys(resumenes).length === 0) {
    return (
      <div className="bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 p-8 text-center">
        <FileText className="w-12 h-12 text-slate-300 dark:text-slate-600 mx-auto mb-3" />
        <p className="text-slate-500 dark:text-slate-400">
          No hay resúmenes disponibles. Ejecuta la Fase 06 (Resumen Inteligente) para generarlos.
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {/* Summary type tabs */}
      <div className="flex flex-wrap gap-2">
        {SUMMARY_TABS.map(({ id, label, icon: Icon }) => {
          const hasData = !!resumenes[id];
          return (
            <button
              key={id}
              onClick={() => hasData && setActiveTab(id)}
              disabled={!hasData}
              className={cn(
                'flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-all',
                activeTab === id
                  ? 'bg-blue-600 text-white shadow-md'
                  : hasData
                  ? 'bg-white dark:bg-slate-800 text-slate-700 dark:text-slate-300 border border-slate-200 dark:border-slate-700 hover:bg-slate-50 dark:hover:bg-slate-700'
                  : 'bg-slate-100 dark:bg-slate-800 text-slate-400 dark:text-slate-600 border border-slate-200 dark:border-slate-700 cursor-not-allowed opacity-60'
              )}
            >
              <Icon className="w-4 h-4" />
              <span>{label}</span>
            </button>
          );
        })}
      </div>

      {/* Category sub-tabs */}
      {currentSummary && (
        <div className="bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 overflow-hidden">
          {/* Category pill nav */}
          <div className="px-4 py-3 border-b border-slate-200 dark:border-slate-700">
            <div className="flex flex-wrap gap-1.5">
              <button
                onClick={() => setActiveCategory('global')}
                className={cn(
                  'flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium transition-all',
                  activeCategory === 'global'
                    ? 'bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300'
                    : 'text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-700'
                )}
              >
                <Globe className="w-3 h-3" />
                Global
              </button>
              {categories.map((cat) => (
                <button
                  key={cat}
                  onClick={() => setActiveCategory(cat)}
                  className={cn(
                    'flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium transition-all',
                    activeCategory === cat
                      ? 'bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300'
                      : 'text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-700'
                  )}
                >
                  <Tag className="w-3 h-3" />
                  {cat}
                </button>
              ))}
            </div>
          </div>

          {/* Content */}
          <div className="p-5">
            {currentContent ? (
              <>
                <div className="prose prose-sm prose-slate dark:prose-invert max-w-none
                  prose-headings:text-slate-900 dark:prose-headings:text-white
                  prose-h1:text-xl prose-h2:text-lg prose-h3:text-base
                  prose-p:text-slate-600 dark:prose-p:text-slate-300
                  prose-li:text-slate-600 dark:prose-li:text-slate-300
                  prose-strong:text-slate-800 dark:prose-strong:text-slate-200">
                  <ReactMarkdown>{currentContent}</ReactMarkdown>
                </div>
                <div className="mt-4 pt-3 border-t border-slate-100 dark:border-slate-700 flex justify-end">
                  <button
                    onClick={() => handleCopy(currentContent, `${activeTab}-${activeCategory}`)}
                    className="flex items-center gap-1.5 text-xs text-slate-500 dark:text-slate-400 hover:text-blue-600 dark:hover:text-blue-400 transition-colors"
                  >
                    {copiedId === `${activeTab}-${activeCategory}` ? (
                      <>
                        <Check className="w-3.5 h-3.5" />
                        Copiado
                      </>
                    ) : (
                      <>
                        <Copy className="w-3.5 h-3.5" />
                        Copiar texto
                      </>
                    )}
                  </button>
                </div>
              </>
            ) : (
              <p className="text-sm text-slate-400 dark:text-slate-500 text-center py-8">
                No hay contenido para esta sección.
              </p>
            )}
          </div>
        </div>
      )}
    </div>
  );
}

/* ──────────────────── Dataset Statistics ──────────────────── */

/** Horizontal bar scaled to percentage */
function PercentBar({ value, max, color }: { value: number; max: number; color: string }) {
  const width = max > 0 ? (value / max) * 100 : 0;
  return (
    <div className="h-2.5 w-full rounded-full bg-slate-100 dark:bg-slate-700">
      <div className={cn('h-full rounded-full transition-all', color)} style={{ width: `${width}%` }} />
    </div>
  );
}

/** Generic stats table card */
function StatsTableCard({
  title,
  icon: Icon,
  headers,
  rows,
  footnote,
}: {
  title: string;
  icon: LucideIcon;
  headers: string[];
  rows: React.ReactNode[][];
  footnote?: string;
}) {
  return (
    <div className="bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 overflow-hidden">
      <div className="px-4 py-3 border-b border-slate-200 dark:border-slate-700 flex items-center gap-2">
        <Icon className="w-4 h-4 text-blue-500" />
        <h3 className="text-sm font-semibold text-slate-900 dark:text-white">{title}</h3>
      </div>
      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-slate-100 dark:border-slate-700">
              {headers.map((h) => (
                <th
                  key={h}
                  className="px-4 py-2 text-left text-xs font-medium text-slate-500 dark:text-slate-400 uppercase tracking-wide"
                >
                  {h}
                </th>
              ))}
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-50 dark:divide-slate-700/50">
            {rows.map((cells, idx) => (
              <tr key={idx} className="hover:bg-slate-50 dark:hover:bg-slate-700/30 transition-colors">
                {cells.map((cell, ci) => (
                  <td key={ci} className="px-4 py-2 text-slate-700 dark:text-slate-300">
                    {cell}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      {footnote && (
        <div className="px-4 py-2 border-t border-slate-100 dark:border-slate-700">
          <p className="text-xs text-slate-400 dark:text-slate-500">{footnote}</p>
        </div>
      )}
    </div>
  );
}

const SENTIMENT_COLORS: Record<string, string> = {
  Positivo: 'bg-green-500',
  Neutro: 'bg-slate-400',
  Negativo: 'bg-red-500',
};

const SUBJECTIVITY_COLORS: Record<string, string> = {
  Subjetiva: 'bg-purple-500',
  Mixta: 'bg-amber-500',
  Objetiva: 'bg-cyan-500',
};

const RATING_COLORS: Record<string, string> = {
  '1': 'bg-red-500',
  '2': 'bg-orange-500',
  '3': 'bg-amber-400',
  '4': 'bg-lime-500',
  '5': 'bg-green-500',
};

function DatasetStatisticsSection({ stats }: { stats: EstadisticasDataset }) {
  const maxSentPct = stats.sentimiento
    ? Math.max(...Object.values(stats.sentimiento).map((v) => v.porcentaje))
    : 0;
  const maxSubjPct = stats.subjetividad
    ? Math.max(...Object.values(stats.subjetividad).map((v) => v.porcentaje))
    : 0;
  const maxCalPct = stats.calificacion
    ? Math.max(...Object.values(stats.calificacion).map((v) => v.porcentaje))
    : 0;
  const maxCatPct = stats.categorias
    ? Math.max(...Object.values(stats.categorias).map((v) => v.porcentaje))
    : 0;

  return (
    <div className="space-y-6">
      {/* Summary row */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <KpiCard
          label="Total Reseñas"
          value={stats.total_registros.toLocaleString()}
          icon={Database}
          color="bg-blue-500"
        />
        {stats.calificacion_promedio != null && (
          <KpiCard
            label="Rating Promedio"
            value={`${stats.calificacion_promedio} / 5`}
            icon={Star}
            color="bg-amber-500"
            subtitle={`Mediana: ${stats.calificacion_mediana}`}
          />
        )}
        {stats.categorias_meta && (
          <KpiCard
            label="Cats / Reseña"
            value={stats.categorias_meta.promedio_categorias_por_review}
            icon={Hash}
            color="bg-indigo-500"
            subtitle={`${stats.categorias_meta.total_asignaciones} asignaciones`}
          />
        )}
        {stats.longitud_texto && (
          <KpiCard
            label="Long. Promedio"
            value={`${stats.longitud_texto.promedio} chars`}
            icon={MessageSquare}
            color="bg-teal-500"
            subtitle={`Min ${stats.longitud_texto.minimo} — Max ${stats.longitud_texto.maximo}`}
          />
        )}
      </div>

      {/* Main distribution tables */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {/* Sentiment */}
        {stats.sentimiento && (
          <StatsTableCard
            title="Distribución de Sentimiento"
            icon={TrendingUp}
            headers={['Sentimiento', 'Cantidad', '%', '']}
            rows={Object.entries(stats.sentimiento).map(([label, { cantidad, porcentaje }]) => [
              <span className="font-medium">{label}</span>,
              <span className="font-semibold tabular-nums">{cantidad.toLocaleString()}</span>,
              <span className="tabular-nums">{porcentaje}%</span>,
              <PercentBar
                value={porcentaje}
                max={maxSentPct}
                color={SENTIMENT_COLORS[label] || 'bg-slate-400'}
              />,
            ])}
          />
        )}

        {/* Subjectivity */}
        {stats.subjetividad && (
          <StatsTableCard
            title="Distribución de Subjetividad"
            icon={MessageSquare}
            headers={['Tipo', 'Cantidad', '%', '']}
            rows={Object.entries(stats.subjetividad).map(([label, { cantidad, porcentaje }]) => [
              <span className="font-medium">{label}</span>,
              <span className="font-semibold tabular-nums">{cantidad.toLocaleString()}</span>,
              <span className="tabular-nums">{porcentaje}%</span>,
              <PercentBar
                value={porcentaje}
                max={maxSubjPct}
                color={SUBJECTIVITY_COLORS[label] || 'bg-slate-400'}
              />,
            ])}
          />
        )}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {/* Rating */}
        {stats.calificacion && (
          <StatsTableCard
            title="Distribución de Calificación"
            icon={Star}
            headers={['Estrellas', 'Cantidad', '%', '']}
            rows={['1', '2', '3', '4', '5']
              .filter((k) => stats.calificacion![k])
              .map((k) => {
                const { cantidad, porcentaje } = stats.calificacion![k];
                return [
                  <span className="font-medium flex items-center gap-1">
                    {'★'.repeat(Number(k))}
                    <span className="text-slate-400">{'★'.repeat(5 - Number(k))}</span>
                  </span>,
                  <span className="font-semibold tabular-nums">{cantidad.toLocaleString()}</span>,
                  <span className="tabular-nums">{porcentaje}%</span>,
                  <PercentBar
                    value={porcentaje}
                    max={maxCalPct}
                    color={RATING_COLORS[k] || 'bg-slate-400'}
                  />,
                ];
              })}
            footnote={stats.calificacion_promedio != null
              ? `Promedio: ${stats.calificacion_promedio} · Mediana: ${stats.calificacion_mediana}`
              : undefined}
          />
        )}

        {/* Temporal */}
        {stats.temporal && (
          <StatsTableCard
            title="Información Temporal"
            icon={Calendar}
            headers={['Métrica', 'Valor']}
            rows={[
              [
                <span className="font-medium">Fecha más antigua</span>,
                <span>{stats.temporal.fecha_min}</span>,
              ],
              [
                <span className="font-medium">Fecha más reciente</span>,
                <span>{stats.temporal.fecha_max}</span>,
              ],
              [
                <span className="font-medium">Rango temporal</span>,
                <span>{stats.temporal.rango_dias.toLocaleString()} días</span>,
              ],
              [
                <span className="font-medium">Con fecha</span>,
                <span>{stats.temporal.registros_con_fecha.toLocaleString()} reseñas</span>,
              ],
              ...(stats.temporal.registros_sin_fecha > 0
                ? [[
                    <span className="font-medium text-amber-600">Sin fecha</span>,
                    <span className="text-amber-600">{stats.temporal.registros_sin_fecha.toLocaleString()} reseñas</span>,
                  ]]
                : []),
            ]}
          />
        )}
      </div>

      {/* Categories table — full width */}
      {stats.categorias && (
        <StatsTableCard
          title="Distribución por Categoría"
          icon={Tag}
          headers={['Categoría', 'Reseñas', '% del Dataset', '']}
          rows={Object.entries(stats.categorias).map(([cat, { cantidad, porcentaje }]) => [
            <span className="font-medium">{cat}</span>,
            <span className="font-semibold tabular-nums">{cantidad.toLocaleString()}</span>,
            <span className="tabular-nums">{porcentaje}%</span>,
            <PercentBar value={porcentaje} max={maxCatPct} color="bg-blue-500" />,
          ])}
          footnote={
            stats.categorias_meta
              ? `${stats.categorias_meta.categorias_unicas} categorías únicas · ${stats.categorias_meta.total_asignaciones} asignaciones totales · ~${stats.categorias_meta.promedio_categorias_por_review} categorías por reseña`
              : undefined
          }
        />
      )}

      {/* Top subtopics */}
      {stats.topicos && stats.topicos.length > 0 && (
        <StatsTableCard
          title="Top Sub-tópicos (máx. 15)"
          icon={Target}
          headers={['#', 'Sub-tópico', 'Menciones', '%']}
          rows={stats.topicos.map((t, i) => [
            <span className="text-slate-400 font-medium">{i + 1}</span>,
            <span className="font-medium">{t.nombre}</span>,
            <span className="font-semibold tabular-nums">{t.cantidad.toLocaleString()}</span>,
            <span className="tabular-nums">{t.porcentaje}%</span>,
          ])}
        />
      )}
    </div>
  );
}

/* ──────────────────── Generation Report ──────────────────── */

interface GenerationReport {
  fecha_generacion: string;
  dataset: {
    total_opiniones: number;
    tiene_fechas: boolean;
    rango_temporal_dias: number;
    categorias_identificadas: number;
    cobertura_topicos: boolean;
  };
  visualizaciones: {
    total_generadas: number;
    total_omitidas: number;
    por_seccion: Record<string, number>;
    lista_generadas: string[];
  };
  omitidas: string[];
  recomendaciones: string[];
}

function GenerationReportCard({ report }: { report: GenerationReport }) {
  const [expanded, setExpanded] = useState(false);

  return (
    <div className="bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 overflow-hidden">
      <button
        onClick={() => setExpanded(!expanded)}
        className="w-full px-4 py-3 border-b border-slate-200 dark:border-slate-700 flex items-center justify-between hover:bg-slate-50 dark:hover:bg-slate-700/50 transition-colors"
      >
        <div className="flex items-center gap-2">
          <BarChart3 className="w-4 h-4 text-blue-500" />
          <h3 className="text-sm font-semibold text-slate-900 dark:text-white">
            Reporte de Generación
          </h3>
          <span className="text-xs text-slate-400">
            {report.visualizaciones.total_generadas} visualizaciones generadas
          </span>
        </div>
        <span className="text-slate-400 text-xs">
          {expanded ? '▲' : '▼'}
        </span>
      </button>
      {expanded && (
        <div className="p-4 space-y-4">
          {/* Section counts */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            {Object.entries(report.visualizaciones.por_seccion).map(([section, count]) => (
              <div key={section} className="bg-slate-50 dark:bg-slate-700/50 rounded-lg p-3 text-center">
                <p className="text-xs text-slate-500 dark:text-slate-400 capitalize">{section}</p>
                <p className="text-lg font-bold text-slate-800 dark:text-slate-200">{count}</p>
              </div>
            ))}
          </div>

          {/* Omitted visualizations warning */}
          {report.omitidas.length > 0 && (
            <div className="bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded-lg p-3">
              <div className="flex items-center gap-2 mb-1">
                <AlertTriangle className="w-4 h-4 text-yellow-600" />
                <p className="text-sm font-medium text-yellow-800 dark:text-yellow-300">
                  Visualizaciones Omitidas ({report.omitidas.length})
                </p>
              </div>
              <ul className="text-xs text-yellow-700 dark:text-yellow-400 space-y-0.5 ml-6 list-disc">
                {report.omitidas.map((item, idx) => (
                  <li key={idx}>{item}</li>
                ))}
              </ul>
            </div>
          )}

          {/* Recommendations */}
          {report.recomendaciones.length > 0 && (
            <div className="space-y-1">
              {report.recomendaciones.map((rec, i) => (
                <p key={i} className="text-xs text-slate-500 dark:text-slate-400 flex items-start gap-1.5">
                  <Info className="w-3 h-3 mt-0.5 shrink-0 text-blue-400" />
                  {rec}
                </p>
              ))}
            </div>
          )}

          {/* Generation date */}
          <p className="text-xs text-slate-400 dark:text-slate-500 text-right">
            Generado: {new Date(report.fecha_generacion).toLocaleString()}
          </p>
        </div>
      )}
    </div>
  );
}

/* ──────────────────── Main Page ──────────────────── */

type InsightsSection = 'overview' | 'statistics' | 'summaries';

export function Insights() {
  const [data, setData] = useState<InsightsData | null>(null);
  const [generationReport, setGenerationReport] = useState<GenerationReport | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [, setError] = useState<string | null>(null);
  const [activeSection, setActiveSection] = useState<InsightsSection>('overview');

  const loadInsights = useCallback(async () => {
    setIsLoading(true);
    setError(null);

    try {
      const pythonDataDir = await window.electronAPI.app.getPythonDataDir();
      const insightsPath = `${pythonDataDir}/visualizaciones/insights_textuales.json`;
      const reportPath = `${pythonDataDir}/visualizaciones/reporte_generacion.json`;

      const result = await window.electronAPI.files.readFile(insightsPath);
      if (result.success && result.content) {
        const parsed: InsightsData = JSON.parse(result.content);
        setData(parsed);
      } else {
        setData(null);
      }

      // Load generation report
      const reportResult = await window.electronAPI.files.readFile(reportPath);
      if (reportResult.success && reportResult.content) {
        const parsedReport: GenerationReport = JSON.parse(reportResult.content);
        setGenerationReport(parsedReport);
      } else {
        setGenerationReport(null);
      }
    } catch (err) {
      console.error('[Insights] Failed to load:', err);
      setData(null);
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    loadInsights();
  }, [loadInsights]);

  const handleExport = async () => {
    if (!data) return;
    const savePath = await window.electronAPI.files.selectDirectory();
    if (!savePath) return;

    // Build a markdown export from all sections
    let md = '# Insights del Análisis de Opiniones Turísticas\n\n';
    md += `> Generado: ${new Date(data.fecha_generacion).toLocaleString()}\n\n`;

    // KPIs
    md += '## KPIs Principales\n\n';
    md += `- **Total de opiniones:** ${data.kpis.total_opiniones}\n`;
    md += `- **Calificación promedio:** ${data.kpis.calificacion_promedio}/5\n`;
    md += `- **Sentimiento positivo:** ${data.kpis.porcentaje_positivo}%\n`;
    md += `- **Sentimiento neutro:** ${data.kpis.porcentaje_neutro}%\n`;
    md += `- **Sentimiento negativo:** ${data.kpis.porcentaje_negativo}%\n`;
    md += `- **Mejor categoría:** ${data.kpis.mejor_categoria}\n`;
    md += `- **Área de oportunidad:** ${data.kpis.peor_categoria}\n\n`;

    // Fortalezas
    md += '## Fortalezas\n\n';
    data.fortalezas.forEach((f, i) => {
      md += `${i + 1}. **${f.categoria}** — ${f.porcentaje_positivo}% positivo (${f.total_menciones} menciones)\n`;
    });
    md += '\n';

    // Debilidades
    md += '## Áreas de Oportunidad\n\n';
    data.debilidades.forEach((d, i) => {
      md += `${i + 1}. **${d.categoria}** — ${d.porcentaje_negativo}% negativo (${d.total_menciones} menciones)\n`;
    });
    md += '\n';

    // Dataset Statistics
    if (data.estadisticas_dataset) {
      const s = data.estadisticas_dataset;
      md += '## Estadísticas del Dataset\n\n';
      md += `- **Total de reseñas:** ${s.total_registros}\n`;
      if (s.sentimiento) {
        md += '\n### Distribución de Sentimiento\n\n| Sentimiento | Cantidad | % |\n|---|---|---|\n';
        for (const [label, v] of Object.entries(s.sentimiento)) {
          md += `| ${label} | ${v.cantidad} | ${v.porcentaje}% |\n`;
        }
      }
      if (s.subjetividad) {
        md += '\n### Distribución de Subjetividad\n\n| Tipo | Cantidad | % |\n|---|---|---|\n';
        for (const [label, v] of Object.entries(s.subjetividad)) {
          md += `| ${label} | ${v.cantidad} | ${v.porcentaje}% |\n`;
        }
      }
      if (s.calificacion) {
        md += '\n### Distribución de Calificación\n\n| Estrellas | Cantidad | % |\n|---|---|---|\n';
        for (const [k, v] of Object.entries(s.calificacion)) {
          md += `| ${'★'.repeat(Number(k))} (${k}) | ${v.cantidad} | ${v.porcentaje}% |\n`;
        }
      }
      if (s.categorias) {
        md += '\n### Distribución por Categoría\n\n| Categoría | Reseñas | % |\n|---|---|---|\n';
        for (const [cat, v] of Object.entries(s.categorias)) {
          md += `| ${cat} | ${v.cantidad} | ${v.porcentaje}% |\n`;
        }
      }
      if (s.topicos && s.topicos.length > 0) {
        md += '\n### Top Sub-tópicos\n\n| # | Sub-tópico | Menciones | % |\n|---|---|---|---|\n';
        s.topicos.forEach((t, i) => {
          md += `| ${i + 1} | ${t.nombre} | ${t.cantidad} | ${t.porcentaje}% |\n`;
        });
      }
      md += '\n';
    }

    // Summaries
    for (const tipo of ['descriptivo', 'estructurado', 'insights'] as const) {
      const s = data.resumenes[tipo];
      if (!s) continue;
      md += `## ${tipo === 'descriptivo' ? 'Resumen Descriptivo' : tipo === 'estructurado' ? 'Resumen Estructurado' : 'Insights Estratégicos'}\n\n`;
      if (s.global) md += `### Global\n\n${s.global}\n\n`;
      if (s.por_categoria) {
        for (const [cat, text] of Object.entries(s.por_categoria)) {
          md += `### ${cat}\n\n${text}\n\n`;
        }
      }
    }

    await window.electronAPI.files.writeFile(`${savePath}/insights_analisis.md`, md);
  };

  const handleOpenFolder = async () => {
    try {
      const pythonDataDir = await window.electronAPI.app.getPythonDataDir();
      await window.electronAPI.files.openPath(`${pythonDataDir}/visualizaciones`);
    } catch (_) { /* ignore */ }
  };

  /* ──── Render ──── */

  return (
    <PageLayout
      title="Insights"
      description="Análisis inteligente y resúmenes ejecutivos del destino"
      headerActions={
        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" onClick={loadInsights} disabled={isLoading}>
            <RefreshCw className={cn('w-4 h-4 mr-2', isLoading && 'animate-spin')} />
            Actualizar
          </Button>
          {data && (
            <>
              <Button variant="outline" size="sm" onClick={handleOpenFolder}>
                <Folder className="w-4 h-4 mr-2" />
                Abrir Carpeta
              </Button>
              <Button size="sm" onClick={handleExport}>
                <Download className="w-4 h-4 mr-2" />
                Exportar
              </Button>
            </>
          )}
        </div>
      }
    >
      {isLoading ? (
        <div className="flex flex-col items-center justify-center h-64">
          <RefreshCw className="w-8 h-8 text-slate-400 animate-spin mb-4" />
          <p className="text-slate-500 dark:text-slate-400">Cargando insights...</p>
        </div>
      ) : !data ? (
        <div className="flex flex-col items-center justify-center h-64 bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700">
          <Lightbulb className="w-16 h-16 text-slate-300 dark:text-slate-600 mb-4" />
          <h3 className="text-lg font-medium text-slate-700 dark:text-slate-300 mb-2">
            No hay insights disponibles
          </h3>
          <p className="text-slate-500 dark:text-slate-400 text-center max-w-md">
            Ejecuta el pipeline completo (incluyendo la Fase 7) para generar los insights del análisis.
          </p>
        </div>
      ) : (
        <div className="space-y-6">
          {/* Section nav */}
          <div className="flex items-center gap-2 border-b border-slate-200 dark:border-slate-700 pb-0">
            {[
              { id: 'overview' as InsightsSection, label: 'Métricas y Rankings', icon: BarChart3 },
              { id: 'statistics' as InsightsSection, label: 'Estadísticas del Dataset', icon: Database },
              { id: 'summaries' as InsightsSection, label: 'Resúmenes Inteligentes', icon: FileText },
            ].map(({ id, label, icon: Icon }) => (
              <button
                key={id}
                onClick={() => setActiveSection(id)}
                className={cn(
                  'flex items-center gap-2 px-4 py-2.5 text-sm font-medium border-b-2 transition-all -mb-px',
                  activeSection === id
                    ? 'border-blue-600 text-blue-600 dark:text-blue-400 dark:border-blue-400'
                    : 'border-transparent text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white hover:border-slate-300'
                )}
              >
                <Icon className="w-4 h-4" />
                {label}
              </button>
            ))}
          </div>

          {activeSection === 'overview' ? (
            <div className="space-y-6">
              {/* KPI Cards */}
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                <KpiCard
                  label="Total Opiniones"
                  value={data.kpis.total_opiniones.toLocaleString()}
                  icon={BarChart3}
                  color="bg-blue-500"
                />
                <KpiCard
                  label="Calificación"
                  value={`${data.kpis.calificacion_promedio} / 5`}
                  icon={Star}
                  color="bg-amber-500"
                  subtitle="Promedio general"
                />
                <KpiCard
                  label="Mejor Categoría"
                  value={data.kpis.mejor_categoria}
                  icon={Award}
                  color="bg-green-500"
                  subtitle={`${data.kpis.porcentaje_positivo}% positivo`}
                />
                <KpiCard
                  label="Área de Oportunidad"
                  value={data.kpis.peor_categoria}
                  icon={AlertTriangle}
                  color="bg-red-500"
                  subtitle={`${data.kpis.porcentaje_negativo}% negativo`}
                />
              </div>

              {/* Sentiment overview bar */}
              <div className="bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 p-4">
                <h3 className="text-sm font-semibold text-slate-900 dark:text-white mb-3">
                  Distribución General de Sentimiento
                </h3>
                <SentimentBar
                  positive={data.kpis.porcentaje_positivo}
                  neutral={data.kpis.porcentaje_neutro}
                  negative={data.kpis.porcentaje_negativo}
                />
              </div>

              {/* Fortalezas & Debilidades */}
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
                <RankingTable
                  title="Fortalezas del Destino"
                  icon={ThumbsUp}
                  items={data.fortalezas}
                  valueKey="porcentaje_positivo"
                  valueColor="text-green-500"
                />
                <RankingTable
                  title="Áreas de Oportunidad"
                  icon={ThumbsDown}
                  items={data.debilidades}
                  valueKey="porcentaje_negativo"
                  valueColor="text-red-500"
                />
              </div>

              {/* Subtópico top + dataset validation collapsible */}
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
                <div className="bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 p-4">
                  <div className="flex items-center gap-2 mb-2">
                    <Target className="w-4 h-4 text-blue-500" />
                    <h3 className="text-sm font-semibold text-slate-900 dark:text-white">
                      Sub-tópico Más Mencionado
                    </h3>
                  </div>
                  <p className="text-lg font-bold text-blue-600 dark:text-blue-400">
                    {data.kpis.subtopico_mas_mencionado}
                  </p>
                </div>

                {/* Validation Card */}
                <div className="bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 overflow-hidden">
                  <div className="px-4 py-3 border-b border-slate-200 dark:border-slate-700 flex items-center gap-2">
                    <Info className="w-4 h-4 text-slate-500" />
                    <h3 className="text-sm font-semibold text-slate-900 dark:text-white">
                      Validación del Dataset
                    </h3>
                  </div>
                  <div className="px-4 pb-4 pt-3 space-y-2 text-sm">
                    <div className="flex justify-between">
                      <span className="text-slate-500">Total opiniones</span>
                      <span className="font-medium text-slate-800 dark:text-slate-200">
                        {data.validacion_dataset.total_opiniones}
                      </span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-slate-500">Fechas disponibles</span>
                      <span className={data.validacion_dataset.tiene_fechas ? 'text-green-600' : 'text-red-500'}>
                        {data.validacion_dataset.tiene_fechas ? `Sí (${data.validacion_dataset.rango_temporal_dias} días)` : 'No'}
                      </span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-slate-500">Categorías</span>
                      <span className="font-medium text-slate-800 dark:text-slate-200">
                        {data.validacion_dataset.categorias_identificadas}
                      </span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-slate-500">Sub-tópicos detectados</span>
                      <span className={data.validacion_dataset.tiene_topicos ? 'text-green-600 font-medium' : 'text-red-500'}>
                        {data.validacion_dataset.tiene_topicos 
                          ? data.validacion_dataset.subtopicos_detectados
                          : 'Ninguno'}
                      </span>
                    </div>
                    {data.validacion_dataset.recomendaciones.length > 0 && (
                      <div className="mt-3 pt-3 border-t border-slate-100 dark:border-slate-700 space-y-1.5">
                        {data.validacion_dataset.recomendaciones.map((rec, i) => (
                          <p key={i} className="text-xs text-slate-500 dark:text-slate-400 flex items-start gap-1.5">
                            <Info className="w-3 h-3 mt-0.5 shrink-0 text-blue-400" />
                            {rec}
                          </p>
                        ))}
                      </div>
                    )}
                  </div>
                </div>
              </div>
              {/* Generation Report */}
              {generationReport && (
                <GenerationReportCard report={generationReport} />
              )}
            </div>
          ) : activeSection === 'statistics' ? (
            /* Statistics tab */
            data.estadisticas_dataset ? (
              <DatasetStatisticsSection stats={data.estadisticas_dataset} />
            ) : (
              <div className="flex flex-col items-center justify-center h-64 bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700">
                <Database className="w-12 h-12 text-slate-300 dark:text-slate-600 mb-3" />
                <p className="text-slate-500 dark:text-slate-400 text-center max-w-md">
                  Las estadísticas del dataset no están disponibles. Re-ejecuta la Fase 7 para generarlas.
                </p>
              </div>
            )
          ) : (
            /* Summaries tab */
            <SummarySection resumenes={data.resumenes} />
          )}

          {/* Generation date footer */}
          <p className="text-xs text-slate-400 dark:text-slate-500 text-right">
            Generado: {new Date(data.fecha_generacion).toLocaleString()}
          </p>
        </div>
      )}
    </PageLayout>
  );
}

export default Insights;
