/**
 * Insights Estratégicos Page
 * ===========================
 * Display a single comprehensive strategic insight generated by Phase 8.
 * This is a holistic data-driven analysis synthesizing all metrics and categories,
 * distinct from the structured summaries in the Resumenes page.
 *
 * Data source:
 *   insights_estrategicos.json (generated by Phase 8 in shared/)
 */

import React, { useState, useEffect, useCallback, useMemo } from 'react';
import { useTranslation } from 'react-i18next';
import {
  Lightbulb,
  RefreshCw,
  Copy,
  Check,
  TrendingUp,
  Calendar,
} from 'lucide-react';
import { PageLayout } from '../components/layout';
import { Button, MarkdownRenderer } from '../components/ui';
import { cn } from '../lib/utils';

/* ──────────────────── Types ──────────────────── */

interface StrategicInsightsFile {
  metadata: {
    fecha_generacion: string;
    total_reviews: number;
  };
  insights: {
    global: string;
  };
}

/* ──────────────────── Main Page ──────────────────── */

export function InsightsEstrategicos() {
  const { t } = useTranslation(['insights', 'common']);
  const [data, setData] = useState<StrategicInsightsFile | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [copiedId, setCopiedId] = useState<string | null>(null);

  const loadInsights = useCallback(async () => {
    setIsLoading(true);
    try {
      const pythonDataDir = await window.electronAPI.app.getPythonDataDir();
      const path = `${pythonDataDir}/shared/insights_estrategicos.json`;
      const result = await window.electronAPI.files.readFile(path);
      if (result.success && result.content) {
        setData(JSON.parse(result.content));
      } else {
        setData(null);
      }
    } catch (err) {
      console.error('[InsightsEstrategicos] Failed to load:', err);
      setData(null);
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    loadInsights();
  }, [loadInsights]);

  const globalContent = useMemo(() => {
    if (!data?.insights?.global) return null;
    
    // Strip markdown code fence wrapper if present
    let content = data.insights.global;
    if (content.startsWith('```markdown\n')) {
      content = content.slice('```markdown\n'.length);
    } else if (content.startsWith('```markdown')) {
      content = content.slice('```markdown'.length);
    } else if (content.startsWith('```\n')) {
      content = content.slice('```\n'.length);
    } else if (content.startsWith('```')) {
      content = content.slice('```'.length);
    }
    
    if (content.endsWith('\n```')) {
      content = content.slice(0, -4);
    } else if (content.endsWith('```')) {
      content = content.slice(0, -3);
    }
    
    return content.trim();
  }, [data]);

  const handleCopy = useCallback(() => {
    if (!globalContent) return;
    navigator.clipboard.writeText(globalContent);
    setCopiedId('insight-global');
    setTimeout(() => setCopiedId(null), 2000);
  }, [globalContent]);

  const handleExport = useCallback(async () => {
    if (!globalContent) return;
    const result = await window.electronAPI.files.selectDirectory();
    if (!result) return;
    try {
      await window.electronAPI.files.writeFile(
        `${result}/insights_estrategicos.md`,
        globalContent
      );
    } catch (err) {
      console.error('Failed to export:', err);
    }
  }, [globalContent]);

  return (
    <PageLayout
      title={t('title')}
      description={t('description')}
      headerActions={
        <div className="flex items-center gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={loadInsights}
            disabled={isLoading}
          >
            <RefreshCw className={cn('w-4 h-4 mr-2', isLoading && 'animate-spin')} />
            {t('actions.reload')}
          </Button>
        </div>
      }
    >
      {isLoading ? (
        <div className="flex items-center justify-center h-64">
          <RefreshCw className="w-8 h-8 animate-spin text-slate-400" />
        </div>
      ) : !globalContent ? (
        <div className="flex flex-col items-center justify-center h-64 bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700">
          <Lightbulb className="w-12 h-12 text-slate-300 dark:text-slate-600 mb-4" />
          <h3 className="text-lg font-medium text-slate-700 dark:text-slate-300 mb-2">
            {t('empty.title')}
          </h3>
          <p className="text-slate-500 dark:text-slate-400 text-center max-w-md">
            {t('empty.description')}
          </p>
        </div>
      ) : (
        <div className="space-y-6">
          {/* Metadata banner */}
          <div className="flex items-center gap-4 text-xs text-slate-500 dark:text-slate-400">
            {data?.metadata?.total_reviews && (
              <span className="flex items-center gap-1">
                <TrendingUp className="w-3.5 h-3.5" />
                {t('metadata.reviews', { count: data.metadata.total_reviews })}
              </span>
            )}
            {data?.metadata?.fecha_generacion && (
              <span className="flex items-center gap-1">
                <Calendar className="w-3.5 h-3.5" />
                {new Date(data.metadata.fecha_generacion).toLocaleString()}
              </span>
            )}
          </div>

          {/* Content card */}
          <div className="bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 overflow-hidden">
            {/* Card header with actions */}
            <div className="px-4 py-3 border-b border-slate-200 dark:border-slate-700 flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Lightbulb className="w-4 h-4 text-blue-500" />
                <h3 className="text-sm font-semibold text-slate-900 dark:text-white">
                  {t('globalInsights')}
                </h3>
              </div>
              <div className="flex items-center gap-1.5">
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleCopy}
                  className="h-7 px-2"
                  title="Copy"
                >
                  {copiedId === 'insight-global' ? (
                    <Check className="w-3.5 h-3.5 text-green-500" />
                  ) : (
                    <Copy className="w-3.5 h-3.5" />
                  )}
                </Button>
              </div>
            </div>
            {/* Content */}
            <div className="px-6 py-6">
              <MarkdownRenderer
                content={globalContent}
                size="lg"
              />
            </div>
          </div>
        </div>
      )}
    </PageLayout>
  );
}

export default InsightsEstrategicos;
