/**
 * Metrics Page
 * ============
 * Professional display of analysis metrics:
 * - KPI cards (total opinions, sentiment %, avg rating, etc.)
 * - Fortalezas & Debilidades ranking tables
 * - Dataset statistics and validation
 *
 * Data source: insights_textuales.json (generated by Phase 8)
 */

import React, { useState, useEffect, useCallback, useMemo } from 'react';
import ReactMarkdown from 'react-markdown';
import {
  Lightbulb,
  RefreshCw,
  Star,
  ThumbsUp,
  ThumbsDown,
  BarChart3,
  FileText,
  Target,
  Award,
  AlertTriangle,
  Copy,
  Check,
  Download,
  Info,
  Folder,
  Globe,
  Tag,
  Database,
  Hash,
  MessageSquare,
  Calendar,
  TrendingUp,
  Timer,
  type LucideIcon,
} from 'lucide-react';
import { PageLayout } from '../components/layout';
import { Button } from '../components/ui';
import { cn } from '../lib/utils';
import { useTranslation } from 'react-i18next';
import { usePipelineStore } from '../stores/pipelineStore';

/* ──────────────────── Helpers ──────────────────── */

/** Remove surrounding quotes from string values */
const cleanQuotes = (value: string | number): string | number => {
  if (typeof value === 'string') {
    return value.replace(/^["']|["']$/g, '');
  }
  return value;
};

/* ──────────────────── Types ──────────────────── */

interface InsightsKpis {
  total_opiniones: number;
  porcentaje_positivo: number;
  porcentaje_neutro: number;
  porcentaje_negativo: number;
  calificacion_promedio: number;
  mejor_categoria: string;
  peor_categoria: string;
  subtopico_mas_mencionado: string;
}

interface FortalezaItem {
  categoria: string;
  porcentaje_positivo: number;
  total_menciones: number;
}

interface DebilidadItem {
  categoria: string;
  porcentaje_negativo: number;
  total_menciones: number;
}

interface ValidacionDataset {
  total_opiniones: number;
  tiene_fechas: boolean;
  rango_temporal_dias: number;
  categorias_identificadas: number;
  tiene_topicos: boolean;
  subtopicos_detectados: number;
  sentimientos: { positivo: number; neutro: number; negativo: number };
  recomendaciones: string[];
}

interface ResumenesData {
  descriptivo?: {
    por_categoria?: Record<string, string>;
    global?: string;
  };
  estructurado?: {
    por_categoria?: Record<string, string>;
    global?: string;
  };
  insights?: {
    por_categoria?: Record<string, string>;
    global?: string;
  };
}

interface DistributionItem {
  cantidad: number;
  porcentaje: number;
}

interface TopicItem {
  nombre: string;
  cantidad: number;
  porcentaje: number;
}

interface EstadisticasDataset {
  total_registros: number;
  sentimiento: Record<string, DistributionItem> | null;
  subjetividad: Record<string, DistributionItem> | null;
  calificacion: Record<string, DistributionItem> | null;
  calificacion_promedio?: number;
  calificacion_mediana?: number;
  categorias: Record<string, DistributionItem> | null;
  categorias_meta?: {
    total_asignaciones: number;
    promedio_categorias_por_review: number;
    categorias_unicas: number;
  };
  topicos: TopicItem[] | null;
  temporal: {
    fecha_min: string;
    fecha_max: string;
    rango_dias: number;
    registros_con_fecha: number;
    registros_sin_fecha: number;
  } | null;
  longitud_texto: {
    promedio: number;
    mediana: number;
    minimo: number;
    maximo: number;
  } | null;
}

interface InsightsData {
  fecha_generacion: string;
  validacion_dataset: ValidacionDataset;
  kpis: InsightsKpis;
  fortalezas: FortalezaItem[];
  debilidades: DebilidadItem[];
  resumenes: ResumenesData;
  estadisticas_dataset?: EstadisticasDataset;
}

/* ──────────────────── Sub-components ──────────────────── */

function KpiCard({
  label,
  value,
  icon: Icon,
  color,
  subtitle,
}: {
  label: string;
  value: string | number;
  icon: React.ComponentType<{ className?: string }>;
  color: string;
  subtitle?: string;
}) {
  return (
    <div className="bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 p-4 flex items-start gap-3">
      <div className={cn('p-2 rounded-lg', color)}>
        <Icon className="w-5 h-5 text-white" />
      </div>
      <div className="min-w-0 flex-1">
        <p className="text-xs font-medium text-slate-500 dark:text-slate-400 uppercase tracking-wide">
          {label}
        </p>
        <p className="text-xl font-bold text-slate-900 dark:text-white mt-0.5 truncate">
          {value}
        </p>
        {subtitle && (
          <p className="text-xs text-slate-400 dark:text-slate-500 mt-0.5 truncate">
            {subtitle}
          </p>
        )}
      </div>
    </div>
  );
}

function SentimentBar({
  positive,
  neutral,
  negative,
}: {
  positive: number;
  neutral: number;
  negative: number;
}) {
  const { t } = useTranslation('metrics');
  return (
    <div className="w-full">
      <div className="flex h-3 rounded-full overflow-hidden bg-slate-100 dark:bg-slate-700">
        <div
          className="bg-green-500 transition-all"
          style={{ width: `${positive}%` }}
          title={`${t('sentiment.positive')}: ${positive}%`}
        />
        <div
          className="bg-slate-400 transition-all"
          style={{ width: `${neutral}%` }}
          title={`${t('sentiment.neutral')}: ${neutral}%`}
        />
        <div
          className="bg-red-500 transition-all"
          style={{ width: `${negative}%` }}
          title={`${t('sentiment.negative')}: ${negative}%`}
        />
      </div>
      <div className="flex justify-between mt-1.5 text-xs text-slate-500 dark:text-slate-400">
        <span className="flex items-center gap-1">
          <span className="w-2 h-2 rounded-full bg-green-500" />
          {t('sentiment.positive')} {positive}%
        </span>
        <span className="flex items-center gap-1">
          <span className="w-2 h-2 rounded-full bg-slate-400" />
          {t('sentiment.neutral')} {neutral}%
        </span>
        <span className="flex items-center gap-1">
          <span className="w-2 h-2 rounded-full bg-red-500" />
          {t('sentiment.negative')} {negative}%
        </span>
      </div>
    </div>
  );
}

function RankingTable({
  title,
  icon: Icon,
  items,
  valueKey,
  valueColor,
}: {
  title: string;
  icon: React.ComponentType<{ className?: string }>;
  items: FortalezaItem[] | DebilidadItem[];
  valueKey: string;
  valueColor: string;
}) {
  const { t } = useTranslation('metrics');
  return (
    <div className="bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 overflow-hidden">
      <div className="px-4 py-3 border-b border-slate-200 dark:border-slate-700 flex items-center gap-2">
        <Icon className={cn('w-5 h-5', valueColor)} />
        <h3 className="font-semibold text-slate-900 dark:text-white text-sm">{title}</h3>
      </div>
      <div className="divide-y divide-slate-100 dark:divide-slate-700/50">
        {items.slice(0, 8).map((item, idx) => (
          <div key={item.categoria} className="flex items-center px-4 py-2.5 gap-3">
            <span
              className={cn(
                'w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold',
                idx < 3
                  ? `${valueColor.replace('text-', 'bg-').replace('500', '100')} ${valueColor}`
                  : 'bg-slate-100 dark:bg-slate-700 text-slate-500 dark:text-slate-400'
              )}
            >
              {idx + 1}
            </span>
            <span className="flex-1 text-sm text-slate-700 dark:text-slate-300 truncate">
              {cleanQuotes(item.categoria)}
            </span>
            <span className={cn('text-sm font-semibold', valueColor)}>
              {Number((item as unknown as Record<string, number>)[valueKey]).toFixed(1)}%
            </span>
            <span className="text-xs text-slate-400 dark:text-slate-500 w-16 text-right">
              {item.total_menciones} {t('ranking.mentions')}
            </span>
          </div>
        ))}
        {items.length === 0 && (
          <p className="px-4 py-6 text-sm text-slate-400 text-center">{t('ranking.noData')}</p>
        )}
      </div>
    </div>
  );
}

/* ──────────────────── Summary Section (tabs) ──────────────────── */

type SummaryType = 'descriptivo' | 'estructurado' | 'insights';

const SUMMARY_TABS: { id: SummaryType; labelKey: string; icon: React.ComponentType<{ className?: string }> }[] = [
  { id: 'descriptivo', labelKey: 'summaries.descriptive', icon: FileText },
  { id: 'estructurado', labelKey: 'summaries.structured', icon: Target },
  { id: 'insights', labelKey: 'summaries.insights', icon: Lightbulb },
];

function SummarySection({ resumenes }: { resumenes: ResumenesData }) {
  const { t } = useTranslation('metrics');
  const [activeTab, setActiveTab] = useState<SummaryType>('descriptivo');
  const [activeCategory, setActiveCategory] = useState<string>('global');
  const [copiedId, setCopiedId] = useState<string | null>(null);

  const currentSummary = resumenes[activeTab];
  const categories = useMemo(() => {
    if (!currentSummary?.por_categoria) return [];
    return Object.keys(currentSummary.por_categoria).sort();
  }, [currentSummary]);

  const currentContent = useMemo(() => {
    if (!currentSummary) return null;
    if (activeCategory === 'global') return currentSummary.global || null;
    return currentSummary.por_categoria?.[activeCategory] || null;
  }, [currentSummary, activeCategory]);

  // Reset category when switching tabs
  useEffect(() => {
    setActiveCategory('global');
  }, [activeTab]);

  const handleCopy = async (text: string, id: string) => {
    await navigator.clipboard.writeText(text);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  if (!resumenes || Object.keys(resumenes).length === 0) {
    return (
      <div className="bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 p-8 text-center">
        <FileText className="w-12 h-12 text-slate-300 dark:text-slate-600 mx-auto mb-3" />
        <p className="text-slate-500 dark:text-slate-400">
          {t('summaries.noSummaries')}
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {/* Summary type tabs */}
      <div className="flex flex-wrap gap-2">
        {SUMMARY_TABS.map(({ id, labelKey, icon: Icon }) => {
          const hasData = !!resumenes[id];
          return (
            <button
              key={id}
              onClick={() => hasData && setActiveTab(id)}
              disabled={!hasData}
              className={cn(
                'flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-all',
                activeTab === id
                  ? 'bg-blue-600 text-white shadow-md cursor-pointer'
                  : hasData
                  ? 'bg-white dark:bg-slate-800 text-slate-700 dark:text-slate-300 border border-slate-200 dark:border-slate-700 hover:bg-slate-50 dark:hover:bg-slate-700 cursor-pointer'
                  : 'bg-slate-100 dark:bg-slate-800 text-slate-400 dark:text-slate-600 border border-slate-200 dark:border-slate-700 cursor-not-allowed opacity-60'
              )}
            >
              <Icon className="w-4 h-4" />
              <span>{t(labelKey)}</span>
            </button>
          );
        })}
      </div>

      {/* Category sub-tabs */}
      {currentSummary && (
        <div className="bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 overflow-hidden">
          {/* Category pill nav */}
          <div className="px-4 py-3 border-b border-slate-200 dark:border-slate-700">
            <div className="flex flex-wrap gap-1.5">
              <button
                onClick={() => setActiveCategory('global')}
                className={cn(
                  'flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium transition-all cursor-pointer',
                  activeCategory === 'global'
                    ? 'bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300'
                    : 'text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-700'
                )}
              >
                <Globe className="w-3 h-3" />
                {t('summaries.global')}
              </button>
              {categories.map((cat) => (
                <button
                  key={cat}
                  onClick={() => setActiveCategory(cat)}
                  className={cn(
                    'flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium transition-all cursor-pointer',
                    activeCategory === cat
                      ? 'bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300'
                      : 'text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-700'
                  )}
                >
                  <Tag className="w-3 h-3" />
                  {cleanQuotes(cat)}
                </button>
              ))}
            </div>
          </div>

          {/* Content */}
          <div className="p-5">
            {currentContent ? (
              <>
                <div className="prose prose-sm prose-slate dark:prose-invert max-w-none
                  prose-headings:text-slate-900 dark:prose-headings:text-white
                  prose-h1:text-xl prose-h2:text-lg prose-h3:text-base
                  prose-p:text-slate-600 dark:prose-p:text-slate-300
                  prose-li:text-slate-600 dark:prose-li:text-slate-300
                  prose-strong:text-slate-800 dark:prose-strong:text-slate-200">
                  <ReactMarkdown>{currentContent}</ReactMarkdown>
                </div>
                <div className="mt-4 pt-3 border-t border-slate-100 dark:border-slate-700 flex justify-end">
                  <button
                    onClick={() => handleCopy(currentContent, `${activeTab}-${activeCategory}`)}
                    className="flex items-center gap-1.5 text-xs text-slate-500 dark:text-slate-400 hover:text-blue-600 dark:hover:text-blue-400 transition-colors"
                  >
                    {copiedId === `${activeTab}-${activeCategory}` ? (
                      <>
                        <Check className="w-3.5 h-3.5" />
                        {t('summaries.copied')}
                      </>
                    ) : (
                      <>
                        <Copy className="w-3.5 h-3.5" />
                        {t('summaries.copyText')}
                      </>
                    )}
                  </button>
                </div>
              </>
            ) : (
              <p className="text-sm text-slate-400 dark:text-slate-500 text-center py-8">
                {t('summaries.noContent')}
              </p>
            )}
          </div>
        </div>
      )}
    </div>
  );
}

/* ──────────────────── Dataset Statistics ──────────────────── */

/** Horizontal bar scaled to percentage */
function PercentBar({ value, max, color }: { value: number; max: number; color: string }) {
  const width = max > 0 ? (value / max) * 100 : 0;
  return (
    <div className="h-2.5 w-full rounded-full bg-slate-100 dark:bg-slate-700">
      <div className={cn('h-full rounded-full transition-all', color)} style={{ width: `${width}%` }} />
    </div>
  );
}

/** Generic stats table card */
function StatsTableCard({
  title,
  icon: Icon,
  headers,
  rows,
  footnote,
}: {
  title: string;
  icon: LucideIcon;
  headers: string[];
  rows: React.ReactNode[][];
  footnote?: string;
}) {
  return (
    <div className="bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 overflow-hidden">
      <div className="px-4 py-3 border-b border-slate-200 dark:border-slate-700 flex items-center gap-2">
        <Icon className="w-4 h-4 text-blue-500" />
        <h3 className="text-sm font-semibold text-slate-900 dark:text-white">{title}</h3>
      </div>
      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-slate-100 dark:border-slate-700">
              {headers.map((h) => (
                <th
                  key={h}
                  className="px-4 py-2 text-left text-xs font-medium text-slate-500 dark:text-slate-400 uppercase tracking-wide"
                >
                  {h}
                </th>
              ))}
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-50 dark:divide-slate-700/50">
            {rows.map((cells, idx) => (
              <tr key={idx} className="hover:bg-slate-50 dark:hover:bg-slate-700/30 transition-colors">
                {cells.map((cell, ci) => (
                  <td key={ci} className="px-4 py-2 text-slate-700 dark:text-slate-300">
                    {cell}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      {footnote && (
        <div className="px-4 py-2 border-t border-slate-100 dark:border-slate-700">
          <p className="text-xs text-slate-400 dark:text-slate-500">{footnote}</p>
        </div>
      )}
    </div>
  );
}

const SENTIMENT_COLORS: Record<string, string> = {
  Positivo: 'bg-green-500',
  Neutro: 'bg-slate-400',
  Negativo: 'bg-red-500',
};

const SUBJECTIVITY_COLORS: Record<string, string> = {
  Subjetiva: 'bg-purple-500',
  Mixta: 'bg-amber-500',
};

const RATING_COLORS: Record<string, string> = {
  '1': 'bg-red-500',
  '2': 'bg-orange-500',
  '3': 'bg-amber-400',
  '4': 'bg-lime-500',
  '5': 'bg-green-500',
};

function DatasetStatisticsSection({ 
  stats, 
  kpis, 
  sentimentBar,
  validacion 
}: { 
  stats: EstadisticasDataset; 
  kpis?: InsightsKpis;
  sentimentBar?: React.ReactNode;
  validacion?: ValidacionDataset;
}) {
  const { t } = useTranslation('metrics');
  const maxSentPct = stats.sentimiento
    ? Math.max(...Object.values(stats.sentimiento).map((v) => v.porcentaje))
    : 0;
  const maxSubjPct = stats.subjetividad
    ? Math.max(...Object.values(stats.subjetividad).map((v) => v.porcentaje))
    : 0;
  const maxCalPct = stats.calificacion
    ? Math.max(...Object.values(stats.calificacion).map((v) => v.porcentaje))
    : 0;
  const maxCatPct = stats.categorias
    ? Math.max(...Object.values(stats.categorias).map((v) => v.porcentaje))
    : 0;

  return (
    <div className="space-y-6">
      {/* Summary row */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <KpiCard
          label={t('kpi.totalReviews')}
          value={stats.total_registros.toLocaleString()}
          icon={Database}
          color="bg-blue-500"
        />
        {stats.calificacion_promedio != null && (
          <KpiCard
            label={t('kpi.avgRating')}
            value={`${stats.calificacion_promedio} / 5`}
            icon={Star}
            color="bg-amber-500"
            subtitle={t('kpi.median', { value: stats.calificacion_mediana })}
          />
        )}
        {stats.categorias_meta && (
          <KpiCard
            label={t('kpi.catsPerReview')}
            value={stats.categorias_meta.promedio_categorias_por_review}
            icon={Hash}
            color="bg-indigo-500"
            subtitle={t('kpi.assignments', { total: stats.categorias_meta.total_asignaciones })}
          />
        )}
        {stats.longitud_texto && (
          <KpiCard
            label={t('kpi.avgLength')}
            value={`${stats.longitud_texto.promedio} ${t('kpi.characters')}`}
            icon={MessageSquare}
            color="bg-teal-500"
            subtitle={t('kpi.minMax', { min: stats.longitud_texto.minimo, max: stats.longitud_texto.maximo })}
          />
        )}
      </div>

      {/* Additional insight KPI cards if available */}
      {kpis && (
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {kpis.mejor_categoria && (
            <KpiCard
              label={t('kpi.bestCategory')}
              value={cleanQuotes(kpis.mejor_categoria)}
              icon={Award}
              color="bg-green-500"
              subtitle={t('kpi.positivePercent', { value: kpis.porcentaje_positivo })}
            />
          )}
          {kpis.peor_categoria && (
            <KpiCard
              label={t('kpi.opportunityArea')}
              value={cleanQuotes(kpis.peor_categoria)}
              icon={AlertTriangle}
              color="bg-red-500"
              subtitle={t('kpi.negativePercent', { value: kpis.porcentaje_negativo })}
            />
          )}
          {kpis.subtopico_mas_mencionado && (
            <KpiCard
              label={t('kpi.mainSubtopic')}
              value={cleanQuotes(kpis.subtopico_mas_mencionado)}
              icon={Target}
              color="bg-blue-500"
            />
          )}
        </div>
      )}

      {/* Sentiment overview bar - passed as parameter */}
      {sentimentBar}

      {/* Main distribution tables */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {/* Sentiment */}
        {stats.sentimiento && (
          <StatsTableCard
            title={t('tables.sentimentDist')}
            icon={TrendingUp}
            headers={[t('headers.sentiment'), t('headers.count'), '%', '']}
            rows={Object.entries(stats.sentimiento).map(([label, { cantidad, porcentaje }]) => [
              <span className="font-medium">{label}</span>,
              <span className="font-semibold tabular-nums">{cantidad.toLocaleString()}</span>,
              <span className="tabular-nums">{porcentaje}%</span>,
              <PercentBar
                value={porcentaje}
                max={maxSentPct}
                color={SENTIMENT_COLORS[label] || 'bg-slate-400'}
              />,
            ])}
          />
        )}

        {/* Subjectivity */}
        {stats.subjetividad && (
          <StatsTableCard
            title={t('tables.subjectivityDist')}
            icon={MessageSquare}
            headers={[t('headers.type'), t('headers.count'), '%', '']}
            rows={Object.entries(stats.subjetividad).map(([label, { cantidad, porcentaje }]) => [
              <span className="font-medium">{label}</span>,
              <span className="font-semibold tabular-nums">{cantidad.toLocaleString()}</span>,
              <span className="tabular-nums">{porcentaje}%</span>,
              <PercentBar
                value={porcentaje}
                max={maxSubjPct}
                color={SUBJECTIVITY_COLORS[label] || 'bg-slate-400'}
              />,
            ])}
            footnote={t('footnotes.subjectivity')}
          />
        )}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {/* Rating */}
        {stats.calificacion && (
          <StatsTableCard
            title={t('tables.ratingDist')}
            icon={Star}
            headers={[t('headers.stars'), t('headers.count'), '%', '']}
            rows={['1', '2', '3', '4', '5']
              .filter((k) => stats.calificacion![k])
              .map((k) => {
                const { cantidad, porcentaje } = stats.calificacion![k];
                return [
                  <span className="font-medium flex items-center gap-1">
                    {'★'.repeat(Number(k))}
                    <span className="text-slate-400">{'★'.repeat(5 - Number(k))}</span>
                  </span>,
                  <span className="font-semibold tabular-nums">{cantidad.toLocaleString()}</span>,
                  <span className="tabular-nums">{porcentaje}%</span>,
                  <PercentBar
                    value={porcentaje}
                    max={maxCalPct}
                    color={RATING_COLORS[k] || 'bg-slate-400'}
                  />,
                ];
              })}
            footnote={stats.calificacion_promedio != null
              ? t('footnotes.rating', { avg: stats.calificacion_promedio, median: stats.calificacion_mediana })
              : undefined}
          />
        )}

        {/* Temporal */}
        {stats.temporal && (
          <StatsTableCard
            title={t('tables.temporalInfo')}
            icon={Calendar}
            headers={[t('headers.metric'), t('headers.value')]}
            rows={[
              [
                <span className="font-medium">{t('temporal.oldest')}</span>,
                <span>{stats.temporal.fecha_min}</span>,
              ],
              [
                <span className="font-medium">{t('temporal.newest')}</span>,
                <span>{stats.temporal.fecha_max}</span>,
              ],
              [
                <span className="font-medium">{t('temporal.range')}</span>,
                <span>{stats.temporal.rango_dias.toLocaleString()} {t('temporal.days')}</span>,
              ],
              [
                <span className="font-medium">{t('temporal.withDate')}</span>,
                <span>{stats.temporal.registros_con_fecha.toLocaleString()} {t('temporal.reviews')}</span>,
              ],
              ...(stats.temporal.registros_sin_fecha > 0
                ? [[
                    <span className="font-medium text-amber-600">{t('temporal.withoutDate')}</span>,
                    <span className="text-amber-600">{stats.temporal.registros_sin_fecha.toLocaleString()} {t('temporal.reviews')}</span>,
                  ]]
                : []),
            ]}
          />
        )}

        {/* Validation Card */}
        {validacion && (
          <div className="bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 overflow-hidden">
            <div className="px-4 py-3 border-b border-slate-200 dark:border-slate-700 flex items-center gap-2">
              <Info className="w-4 h-4 text-slate-500 dark:text-slate-400" />
              <h3 className="text-sm font-semibold text-slate-900 dark:text-white">
                {t('tables.datasetValidation')}
              </h3>
            </div>
            <div className="px-4 pb-4 pt-3 space-y-2 text-sm">
              <div className="flex justify-between">
                <span className="text-slate-500 dark:text-slate-400">{t('validationCard.datesAvailable')}</span>
                <span className={validacion.tiene_fechas ? 'text-green-600' : 'text-red-500'}>
                  {validacion.tiene_fechas ? `${t('validationCard.yes')} ${t('validationCard.daysCount', { days: validacion.rango_temporal_dias })}` : t('validationCard.no')}
                </span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-500 dark:text-slate-400">{t('validationCard.categoriesIdentified')}</span>
                <span className="font-medium text-slate-800 dark:text-slate-200">
                  {validacion.categorias_identificadas}
                </span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-500 dark:text-slate-400">{t('validationCard.subtopicsDetected')}</span>
                <span className={validacion.tiene_topicos ? 'text-green-600 font-medium' : 'text-red-500'}>
                  {validacion.tiene_topicos 
                    ? validacion.subtopicos_detectados
                    : t('validationCard.none')}
                </span>
              </div>
              {validacion.recomendaciones.length > 0 && (
                <div className="mt-3 pt-3 border-t border-slate-100 dark:border-slate-700 space-y-1.5">
                  {validacion.recomendaciones.map((rec, i) => (
                    <p key={i} className="text-xs text-slate-500 dark:text-slate-400 flex items-start gap-1.5">
                      <Info className="w-3 h-3 mt-0.5 shrink-0 text-blue-400" />
                      {rec}
                    </p>
                  ))}
                </div>
              )}
            </div>
          </div>
        )}
      </div>

      {/* Categories table — 2 columns */}
      {stats.categorias && (() => {
        const entries = Object.entries(stats.categorias);
        const half = Math.ceil(entries.length / 2);
        const leftHalf = entries.slice(0, half);
        const rightHalf = entries.slice(half);
        
        return (
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
            <StatsTableCard
              title={t('tables.categoryDist1')}
              icon={Tag}
              headers={[t('headers.category'), t('headers.reviews'), '%', '']}
              rows={leftHalf.map(([cat, { cantidad, porcentaje }]) => [
                <span className="font-medium">{cleanQuotes(cat)}</span>,
                <span className="font-semibold tabular-nums">{cantidad.toLocaleString()}</span>,
                <span className="tabular-nums">{porcentaje}%</span>,
                <PercentBar value={porcentaje} max={maxCatPct} color="bg-blue-500" />,
              ])}
            />
            <StatsTableCard
              title={t('tables.categoryDist2')}
              icon={Tag}
              headers={[t('headers.category'), t('headers.reviews'), '%', '']}
              rows={rightHalf.map(([cat, { cantidad, porcentaje }]) => [
                <span className="font-medium">{cleanQuotes(cat)}</span>,
                <span className="font-semibold tabular-nums">{cantidad.toLocaleString()}</span>,
                <span className="tabular-nums">{porcentaje}%</span>,
                <PercentBar value={porcentaje} max={maxCatPct} color="bg-blue-500" />,
              ])}
              footnote={
                stats.categorias_meta
                  ? t('footnotes.categories', { n: stats.categorias_meta.categorias_unicas, assignments: stats.categorias_meta.total_asignaciones, perReview: stats.categorias_meta.promedio_categorias_por_review })
                  : undefined
              }
            />
          </div>
        );
      })()}

      {/* Top subtopics — 2 columns */}
      {stats.topicos && stats.topicos.length > 0 && (() => {
        const half = Math.ceil(stats.topicos.length / 2);
        const leftHalf = stats.topicos.slice(0, half);
        const rightHalf = stats.topicos.slice(half);
        
        return (
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
            <StatsTableCard
              title={t('tables.topSubtopics1')}
              icon={Target}
              headers={['#', t('headers.subtopic'), t('headers.mentions'), '%']}
              rows={leftHalf.map((t, i) => [
                <span className="text-slate-400 font-medium">{i + 1}</span>,
                <span className="font-medium">{cleanQuotes(t.nombre)}</span>,
                <span className="font-semibold tabular-nums">{t.cantidad.toLocaleString()}</span>,
                <span className="tabular-nums">{t.porcentaje}%</span>,
              ])}
            />
            <StatsTableCard
              title={t('tables.topSubtopics2')}
              icon={Target}
              headers={['#', t('headers.subtopic'), t('headers.mentions'), '%']}
              rows={rightHalf.map((t, i) => [
                <span className="text-slate-400 font-medium">{half + i + 1}</span>,
                <span className="font-medium">{cleanQuotes(t.nombre)}</span>,
                <span className="font-semibold tabular-nums">{t.cantidad.toLocaleString()}</span>,
                <span className="tabular-nums">{t.porcentaje}%</span>,
              ])}
            />
          </div>
        );
      })()}
    </div>
  );
}

/* ──────────────────── Generation Report ──────────────────── */

interface GenerationReport {
  fecha_generacion: string;
  dataset: {
    total_opiniones: number;
    tiene_fechas: boolean;
    tiene_calificacion: boolean;
    rango_temporal_dias: number;
    categorias_identificadas: number;
    cobertura_topicos: boolean;
  };
  visualizaciones: {
    total_generadas: number;
    total_omitidas: number;
    por_seccion: Record<string, number>;
    lista_generadas: string[];
  };
  omitidas: string[];
  recomendaciones: string[];
}

function GenerationReportCard({ report }: { report: GenerationReport }) {
  const { t } = useTranslation('metrics');
  return (
    <div className="bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 overflow-hidden">
      <div className="px-4 py-3 border-b border-slate-200 dark:border-slate-700 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <BarChart3 className="w-4 h-4 text-blue-500" />
          <h3 className="text-sm font-semibold text-slate-900 dark:text-white">
            {t('tables.generationReport')}
          </h3>
          <span className="text-xs text-slate-400">
            {report.visualizaciones.total_generadas} {t('generation.visualizationsGenerated')}
          </span>
        </div>
      </div>
      <div className="p-4 space-y-4">
        {/* Section counts */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
          {Object.entries(report.visualizaciones.por_seccion).map(([section, count]) => (
            <div key={section} className="bg-slate-50 dark:bg-slate-700/50 rounded-lg p-3 text-center">
              <p className="text-xs text-slate-500 dark:text-slate-400 capitalize">{section}</p>
              <p className="text-lg font-bold text-slate-800 dark:text-slate-200">{count}</p>
            </div>
          ))}
        </div>

        {/* Omitted visualizations warning */}
        {report.omitidas.length > 0 && (
          <div className="bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded-lg p-3">
            <div className="flex items-center gap-2 mb-1">
              <AlertTriangle className="w-4 h-4 text-yellow-600" />
              <p className="text-sm font-medium text-yellow-800 dark:text-yellow-300">
                {t('generation.skippedTitle')} ({report.omitidas.length})
              </p>
            </div>
            <ul className="text-xs text-yellow-700 dark:text-yellow-400 space-y-0.5 ml-6 list-disc">
              {report.omitidas.map((item, idx) => (
                <li key={idx}>{item}</li>
              ))}
            </ul>
          </div>
        )}

        {/* Recommendations */}
        {report.recomendaciones.length > 0 && (
          <div className="space-y-1">
            {report.recomendaciones.map((rec, i) => (
              <p key={i} className="text-xs text-slate-500 dark:text-slate-400 flex items-start gap-1.5">
                <Info className="w-3 h-3 mt-0.5 shrink-0 text-blue-400" />
                {rec}
              </p>
            ))}
          </div>
        )}

        {/* Generation date */}
        <p className="text-xs text-slate-400 dark:text-slate-500 text-right">
          {t('generated')}{new Date(report.fecha_generacion).toLocaleString()}
        </p>
      </div>
    </div>
  );
}

/* ──────────────────── Pipeline Timing Section ──────────────────── */

/** Format duration in milliseconds to a human-readable string */
function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  const totalSeconds = Math.floor(ms / 1000);
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = totalSeconds % 60;
  if (hours > 0) return `${hours}h ${minutes}m ${seconds}s`;
  if (minutes > 0) return `${minutes}m ${seconds}s`;
  return `${seconds}s`;
}

function PipelineTimingSection() {
  const { t } = useTranslation('metrics');
  const phases = usePipelineStore((state) => state.phases);
  const pipelineDuration = usePipelineStore((state) => state.pipelineDuration);
  const pipelineStartedAt = usePipelineStore((state) => state.pipelineStartedAt);
  const pipelineCompletedAt = usePipelineStore((state) => state.pipelineCompletedAt);
  const lastTimingRecord = usePipelineStore((state) => state.lastTimingRecord);

  // Gather per-phase timing from current phases state
  const phaseTimings = Object.values(phases)
    .filter((p) => p.duration !== undefined && p.duration > 0)
    .sort((a, b) => a.phase - b.phase);

  // If no current phase timings, try lastTimingRecord
  const hasCurrentTimings = phaseTimings.length > 0;
  const recordPhases = lastTimingRecord
    ? Object.entries(lastTimingRecord.phases)
        .map(([k, v]) => ({ phase: Number(k), ...v }))
        .sort((a, b) => a.phase - b.phase)
    : [];

  const displayPhases = hasCurrentTimings ? phaseTimings : recordPhases;
  const totalDuration = hasCurrentTimings
    ? pipelineDuration
    : lastTimingRecord?.duration ?? null;
  const displayStartedAt = hasCurrentTimings
    ? pipelineStartedAt
    : lastTimingRecord?.startedAt ?? null;
  const displayCompletedAt = hasCurrentTimings
    ? pipelineCompletedAt
    : lastTimingRecord?.completedAt ?? null;

  if (displayPhases.length === 0 && totalDuration === null) {
    return null;
  }

  // Find the longest phase for bar scaling
  const maxDuration = Math.max(...displayPhases.map((p) => ('duration' in p ? p.duration ?? 0 : 0)));

  return (
    <div className="bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 overflow-hidden">
      <div className="px-4 py-3 border-b border-slate-200 dark:border-slate-700 flex items-center gap-2">
        <Timer className="w-5 h-5 text-blue-500" />
        <h3 className="font-semibold text-slate-900 dark:text-white text-sm">
          {t('pipelineTiming.title')}
        </h3>
      </div>
      <div className="p-4 space-y-4">
        {/* Total duration */}
        {totalDuration !== null && totalDuration > 0 && (
          <div className="flex items-center justify-between bg-blue-50 dark:bg-blue-900/20 rounded-lg px-4 py-3">
            <div>
              <p className="text-sm font-medium text-blue-800 dark:text-blue-300">
                {t('pipelineTiming.totalTime')}
              </p>
              {displayStartedAt && displayCompletedAt && (
                <p className="text-xs text-blue-600 dark:text-blue-400 mt-0.5">
                  {new Date(displayStartedAt).toLocaleString()} — {new Date(displayCompletedAt).toLocaleString()}
                </p>
              )}
            </div>
            <span className="text-lg font-bold font-mono text-blue-700 dark:text-blue-300">
              {formatDuration(totalDuration)}
            </span>
          </div>
        )}

        {/* Per-phase timing table */}
        {displayPhases.length > 0 && (
          <div className="divide-y divide-slate-100 dark:divide-slate-700/50">
            {displayPhases.map((p) => {
              const dur = 'duration' in p ? (p.duration ?? 0) : 0;
              const name = t(`common:phases.${p.phase}.name`);
              const phaseNum = p.phase;
              const phaseStatus = 'status' in p ? p.status : 'completed';
              const barWidth = maxDuration > 0 ? (dur / maxDuration) * 100 : 0;

              return (
                <div key={phaseNum} className="flex items-center gap-3 py-2.5">
                  <span className="w-7 h-7 rounded-full bg-slate-100 dark:bg-slate-700 flex items-center justify-center text-xs font-bold text-slate-600 dark:text-slate-300 shrink-0">
                    {phaseNum}
                  </span>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center justify-between mb-1">
                      <span className="text-sm text-slate-700 dark:text-slate-300 truncate">
                        {name}
                      </span>
                      <span className={cn(
                        'text-sm font-mono font-semibold shrink-0 ml-2',
                        phaseStatus === 'completed'
                          ? 'text-green-600 dark:text-green-400'
                          : 'text-red-600 dark:text-red-400'
                      )}>
                        {formatDuration(dur)}
                      </span>
                    </div>
                    <div className="h-1.5 rounded-full bg-slate-100 dark:bg-slate-700 overflow-hidden">
                      <div
                        className={cn(
                          'h-full rounded-full transition-all',
                          phaseStatus === 'completed' ? 'bg-green-500' : 'bg-red-500'
                        )}
                        style={{ width: `${barWidth}%` }}
                      />
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}

/* ──────────────────── Main Page ──────────────────── */

export function Metrics() {
  const { t } = useTranslation('metrics');
  const [data, setData] = useState<InsightsData | null>(null);
  const [generationReport, setGenerationReport] = useState<GenerationReport | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [, setError] = useState<string | null>(null);

  const loadInsights = useCallback(async () => {
    setIsLoading(true);
    setError(null);

    try {
      const pythonDataDir = await window.electronAPI.app.getPythonDataDir();
      const insightsPath = `${pythonDataDir}/visualizaciones/insights_textuales.json`;
      const reportPath = `${pythonDataDir}/visualizaciones/reporte_generacion.json`;

      const result = await window.electronAPI.files.readFile(insightsPath);
      if (result.success && result.content) {
        const parsed: InsightsData = JSON.parse(result.content);
        setData(parsed);
      } else {
        setData(null);
      }

      // Load generation report
      const reportResult = await window.electronAPI.files.readFile(reportPath);
      if (reportResult.success && reportResult.content) {
        const parsedReport: GenerationReport = JSON.parse(reportResult.content);
        setGenerationReport(parsedReport);
      } else {
        setGenerationReport(null);
      }
    } catch (err) {
      console.error('[Metrics] Failed to load:', err);
      setData(null);
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    loadInsights();
  }, [loadInsights]);

  const handleExport = async () => {
    if (!data) return;
    const savePath = await window.electronAPI.files.selectDirectory();
    if (!savePath) return;

    // Build a markdown export from all sections
    let md = `${t('export.heading')}\n\n`;
    md += `${t('export.generatedPrefix')}${new Date(data.fecha_generacion).toLocaleString()}\n\n`;

    // KPIs
    md += `${t('export.kpisHeading')}\n\n`;
    md += `- ${t('export.totalOpinions')} ${data.kpis.total_opiniones}\n`;
    md += `- ${t('export.avgRating')} ${data.kpis.calificacion_promedio}/5\n`;
    md += `- ${t('export.positiveSentiment')} ${data.kpis.porcentaje_positivo}%\n`;
    md += `- ${t('export.neutralSentiment')} ${data.kpis.porcentaje_neutro}%\n`;
    md += `- ${t('export.negativeSentiment')} ${data.kpis.porcentaje_negativo}%\n`;
    md += `- ${t('export.bestCategory')} ${cleanQuotes(data.kpis.mejor_categoria)}\n`;
    md += `- ${t('export.opportunityArea')} ${cleanQuotes(data.kpis.peor_categoria)}\n\n`;

    // Fortalezas
    md += `${t('export.strengthsHeading')}\n\n`;
    data.fortalezas.forEach((f, i) => {
      md += `${i + 1}. **${cleanQuotes(f.categoria)}** — ${f.porcentaje_positivo}% ${t('export.positive')} (${f.total_menciones} ${t('export.mentionsLabel')})\n`;
    });
    md += '\n';

    // Debilidades
    md += `${t('export.opportunitiesHeading')}\n\n`;
    data.debilidades.forEach((d, i) => {
      md += `${i + 1}. **${cleanQuotes(d.categoria)}** — ${d.porcentaje_negativo}% ${t('export.negative')} (${d.total_menciones} ${t('export.mentionsLabel')})\n`;
    });
    md += '\n';

    // Dataset Statistics
    if (data.estadisticas_dataset) {
      const s = data.estadisticas_dataset;
      md += `${t('export.statsHeading')}\n\n`;
      md += `- ${t('export.totalReviews')} ${s.total_registros}\n`;
      if (s.sentimiento) {
        md += `\n${t('export.sentimentDistHeading')}\n\n| ${t('headers.sentiment')} | ${t('headers.count')} | % |\n|---|---|---|\n`;
        for (const [label, v] of Object.entries(s.sentimiento)) {
          md += `| ${label} | ${v.cantidad} | ${v.porcentaje}% |\n`;
        }
      }
      if (s.subjetividad) {
        md += `\n${t('export.subjectivityDistHeading')}\n\n| ${t('headers.type')} | ${t('headers.count')} | % |\n|---|---|---|\n`;
        for (const [label, v] of Object.entries(s.subjetividad)) {
          md += `| ${label} | ${v.cantidad} | ${v.porcentaje}% |\n`;
        }
        md += `\n> ${t('export.methodNote')}\n`;
      }
      if (s.calificacion) {
        md += `\n${t('export.ratingDistHeading')}\n\n| ${t('headers.stars')} | ${t('headers.count')} | % |\n|---|---|---|\n`;
        for (const [k, v] of Object.entries(s.calificacion)) {
          md += `| ${'★'.repeat(Number(k))} (${k}) | ${v.cantidad} | ${v.porcentaje}% |\n`;
        }
      }
      if (s.categorias) {
        md += `\n${t('export.categoryDistHeading')}\n\n| ${t('headers.category')} | ${t('headers.reviews')} | % |\n|---|---|---|\n`;
        for (const [cat, v] of Object.entries(s.categorias)) {
          md += `| ${cleanQuotes(cat)} | ${v.cantidad} | ${v.porcentaje}% |\n`;
        }
      }
      if (s.topicos && s.topicos.length > 0) {
        md += `\n${t('export.topSubtopicsHeading')}\n\n| # | ${t('headers.subtopic')} | ${t('headers.mentions')} | % |\n|---|---|---|---|\n`;
        s.topicos.forEach((tp, i) => {
          md += `| ${i + 1} | ${cleanQuotes(tp.nombre)} | ${tp.cantidad} | ${tp.porcentaje}% |\n`;
        });
      }
      md += '\n';
    }

    // Summaries
    for (const tipo of ['descriptivo', 'estructurado', 'insights'] as const) {
      const s = data.resumenes[tipo];
      if (!s) continue;
      md += `## ${tipo === 'descriptivo' ? t('summaries.descriptive') : tipo === 'estructurado' ? t('summaries.structured') : t('summaries.insights')}\n\n`;
      if (s.global) md += `### ${t('summaries.global')}\n\n${s.global}\n\n`;
      if (s.por_categoria) {
        for (const [cat, text] of Object.entries(s.por_categoria)) {
          md += `### ${cleanQuotes(cat)}\n\n${text}\n\n`;
        }
      }
    }

    await window.electronAPI.files.writeFile(`${savePath}/insights_analisis.md`, md);
  };

  const handleOpenFolder = async () => {
    try {
      const pythonDataDir = await window.electronAPI.app.getPythonDataDir();
      await window.electronAPI.files.openPath(`${pythonDataDir}/visualizaciones`);
    } catch (_) { /* ignore */ }
  };

  /* ──── Render ──── */

  return (
    <PageLayout
      title={t('title')}
      description={t('description')}
      headerActions={
        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" onClick={loadInsights} disabled={isLoading}>
            <RefreshCw className={cn('w-4 h-4 mr-2', isLoading && 'animate-spin')} />
            {t('actions.refresh')}
          </Button>
          {data && (
            <>
              <Button variant="outline" size="sm" onClick={handleOpenFolder}>
                <Folder className="w-4 h-4 mr-2" />
                {t('actions.openFolder')}
              </Button>
              <Button size="sm" onClick={handleExport}>
                <Download className="w-4 h-4 mr-2" />
                {t('actions.export')}
              </Button>
            </>
          )}
        </div>
      }
    >
      {isLoading ? (
        <div className="flex flex-col items-center justify-center h-64">
          <RefreshCw className="w-8 h-8 text-slate-400 animate-spin mb-4" />
          <p className="text-slate-500 dark:text-slate-400">{t('loading')}</p>
        </div>
      ) : !data ? (
        <div className="flex flex-col items-center justify-center h-64 bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700">
          <BarChart3 className="w-16 h-16 text-slate-300 dark:text-slate-600 mb-4" />
          <h3 className="text-lg font-medium text-slate-700 dark:text-slate-300 mb-2">
            {t('empty.title')}
          </h3>
          <p className="text-slate-500 dark:text-slate-400 text-center max-w-md">
            {t('empty.description')}
          </p>
        </div>
      ) : (
        <div className="space-y-6">
          {/* Dataset Statistics Section - Phase 2 data prioritized */}
          {data.estadisticas_dataset ? (
            <>
              <DatasetStatisticsSection 
                stats={data.estadisticas_dataset} 
                kpis={data.kpis}
                validacion={data.validacion_dataset}
                sentimentBar={
                  <div className="bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 p-4">
                    <h3 className="text-sm font-semibold text-slate-900 dark:text-white mb-3">
                      {t('sentiment.distribution')}
                    </h3>
                    <SentimentBar
                      positive={data.kpis.porcentaje_positivo}
                      neutral={data.kpis.porcentaje_neutro}
                      negative={data.kpis.porcentaje_negativo}
                    />
                  </div>
                }
              />

              {/* Fortalezas & Debilidades */}
              {(data.fortalezas.length > 0 || data.debilidades.length > 0) && (
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
                  {data.fortalezas.length > 0 && (
                    <RankingTable
                      title={t('ranking.strengths')}
                      icon={ThumbsUp}
                      items={data.fortalezas}
                      valueKey="porcentaje_positivo"
                      valueColor="text-green-500"
                    />
                  )}
                  {data.debilidades.length > 0 && (
                    <RankingTable
                      title={t('ranking.opportunities')}
                      icon={ThumbsDown}
                      items={data.debilidades}
                      valueKey="porcentaje_negativo"
                      valueColor="text-red-500"
                    />
                  )}
                </div>
              )}

              {/* Generation Report */}
              {generationReport && (
                <GenerationReportCard report={generationReport} />
              )}

              {/* Pipeline Timing */}
              <PipelineTimingSection />
            </>
          ) : (
            <div className="flex flex-col items-center justify-center h-64 bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700">
              <Database className="w-12 h-12 text-slate-300 dark:text-slate-600 mb-3" />
              <p className="text-slate-500 dark:text-slate-400 text-center max-w-md">
                {t('missingStats')}
              </p>
            </div>
          )}

          {/* Generation date footer */}
          <p className="text-xs text-slate-400 dark:text-slate-500 text-right">
            {t('generated')}{new Date(data.fecha_generacion).toLocaleString()}
          </p>
        </div>
      )}
    </PageLayout>
  );
}

export default Metrics;
