/**
 * Resumenes Page
 * ==============
 * Display LLM-generated structured summaries from Phase 7.
 *
 * Data source:
 *   insights_textuales.json (generated by Phase 9 from Phase 7 output)
 */

import React, { useState, useEffect, useCallback, useMemo } from 'react';
import ReactMarkdown from 'react-markdown';
import { useTranslation } from 'react-i18next';
import {
  RefreshCw,
  FileText,
  Copy,
  Check,
  Download,
  Folder,
  Globe,
  Tag,
} from 'lucide-react';
import { PageLayout } from '../components/layout';
import { Button } from '../components/ui';
import { cn } from '../lib/utils';

/* ──────────────────── Helpers ──────────────────── */

/** Translate category names from Python to current language */
const translateCategoryName = (category: string, t: (key: string) => string): string => {
  const cleaned = typeof category === 'string' ? category.replace(/^["']|["']$/g, '') : String(category);
  const key = `common:dataLabels.categories.${cleaned}`;
  const translated = t(key);
  return translated !== key ? translated : cleaned;
};

/* ──────────────────── Types ──────────────────── */

interface SummaryBlock {
  por_categoria?: Record<string, string>;
  global?: string;
}

interface ResumenesData {
  estructurado?: SummaryBlock;
}

interface InsightsDataFile {
  fecha_generacion: string;
  resumenes: ResumenesData;
}

/* ──────────────────── Main Page ──────────────────── */

export function Resumenes() {
  const { t } = useTranslation(['resumenes', 'common']);
  const [data, setData] = useState<InsightsDataFile | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [activeCategory, setActiveCategory] = useState<string>('global');
  const [copiedId, setCopiedId] = useState<string | null>(null);

  const loadResumenes = useCallback(async () => {
    setIsLoading(true);
    try {
      const pythonDataDir = await window.electronAPI.app.getPythonDataDir();
      const insightsPath = `${pythonDataDir}/visualizaciones/insights_textuales.json`;
      const result = await window.electronAPI.files.readFile(insightsPath);
      if (result.success && result.content) {
        setData(JSON.parse(result.content));
      } else {
        setData(null);
      }
    } catch (err) {
      console.error('[Resumenes] Failed to load:', err);
      setData(null);
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    loadResumenes();
  }, [loadResumenes]);

  const summaryBlock = data?.resumenes?.estructurado || null;

  const categories = useMemo(() => {
    if (!summaryBlock?.por_categoria) return [];
    return Object.keys(summaryBlock.por_categoria).sort();
  }, [summaryBlock]);

  const currentContent = useMemo(() => {
    if (!summaryBlock) return t('emptyGlobal');
    if (activeCategory === 'global') {
      return summaryBlock.global || t('emptyGlobal');
    }
    return summaryBlock.por_categoria?.[activeCategory] || t('emptyCategory');
  }, [summaryBlock, activeCategory, t]);

  const handleCopy = useCallback((id: string, text: string) => {
    navigator.clipboard.writeText(text);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  }, []);

  const handleExportCategory = useCallback(async () => {
    if (!currentContent) return;
    const fileName = `resumen_estructurado_${activeCategory}.md`;
    const result = await window.electronAPI.files.selectDirectory();
    if (!result) return;
    try {
      await window.electronAPI.files.writeFile(`${result}/${fileName}`, currentContent);
    } catch (err) {
      console.error('Failed to export:', err);
    }
  }, [activeCategory, currentContent]);

  const handleExportAll = async () => {
    if (!summaryBlock) return;
    const result = await window.electronAPI.files.selectDirectory();
    if (!result) return;
    try {
      if (summaryBlock.global) {
        await window.electronAPI.files.writeFile(
          `${result}/resumen_estructurado_global.md`,
          summaryBlock.global
        );
      }
      if (summaryBlock.por_categoria) {
        for (const [category, content] of Object.entries(summaryBlock.por_categoria)) {
          await window.electronAPI.files.writeFile(
            `${result}/resumen_estructurado_${category}.md`,
            content
          );
        }
      }
    } catch (err) {
      console.error('Failed to export all:', err);
    }
  };

  return (
    <PageLayout
      title={t('title')}
      description={t('description')}
      headerActions={
        <div className="flex items-center gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={loadResumenes}
            disabled={isLoading}
          >
            <RefreshCw className={cn('w-4 h-4 mr-2', isLoading && 'animate-spin')} />
            {t('actions.reload')}
          </Button>
          {summaryBlock && (
            <Button
              variant="outline"
              size="sm"
              onClick={handleExportAll}
            >
              <Folder className="w-4 h-4 mr-2" />
              {t('actions.exportAll')}
            </Button>
          )}
        </div>
      }
    >
      {isLoading ? (
        <div className="flex items-center justify-center h-64">
          <RefreshCw className="w-8 h-8 animate-spin text-slate-400" />
        </div>
      ) : !summaryBlock ? (
        <div className="flex flex-col items-center justify-center h-64 bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700">
          <FileText className="w-16 h-16 text-slate-300 dark:text-slate-600 mb-4" />
          <h3 className="text-lg font-medium text-slate-700 dark:text-slate-300 mb-2">
            {t('empty.title')}
          </h3>
          <p className="text-slate-500 dark:text-slate-400 text-center max-w-md">
            {t('empty.description')}
          </p>
        </div>
      ) : (
        <div className="space-y-4">
          {/* Category filters */}
          {categories.length > 0 && (
            <div className="flex items-center gap-2 flex-wrap">
              <button
                onClick={() => setActiveCategory('global')}
                className={cn(
                  'flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-colors cursor-pointer',
                  activeCategory === 'global'
                    ? 'bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 border border-blue-300 dark:border-blue-700'
                    : 'bg-white dark:bg-slate-800 text-slate-600 dark:text-slate-400 border border-slate-200 dark:border-slate-700 hover:border-blue-300 dark:hover:border-blue-700'
                )}
              >
                <Globe className="w-3.5 h-3.5" />
                {t('globalSummary')}
              </button>
              {categories.map((cat) => (
                <button
                  key={cat}
                  onClick={() => setActiveCategory(cat)}
                  className={cn(
                    'flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-colors cursor-pointer',
                    activeCategory === cat
                      ? 'bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 border border-blue-300 dark:border-blue-700'
                      : 'bg-white dark:bg-slate-800 text-slate-600 dark:text-slate-400 border border-slate-200 dark:border-slate-700 hover:border-blue-300 dark:hover:border-blue-700'
                  )}
                >
                  <Tag className="w-3.5 h-3.5" />
                  {translateCategoryName(cat, t)}
                </button>
              ))}
            </div>
          )}

          {/* Content card */}
          <div className="bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 overflow-hidden">
            <div className="px-4 py-3 border-b border-slate-200 dark:border-slate-700 flex items-center justify-between">
              <div className="flex items-center gap-2">
                {activeCategory === 'global' ? (
                  <Globe className="w-4 h-4 text-blue-500" />
                ) : (
                  <Tag className="w-4 h-4 text-blue-500" />
                )}
                <h3 className="text-sm font-semibold text-slate-900 dark:text-white">
                  {activeCategory === 'global' ? t('globalSummary') : translateCategoryName(activeCategory, t)}
                </h3>
              </div>
              <div className="flex items-center gap-1.5">
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => handleCopy(`structured-${activeCategory}`, currentContent)}
                  className="h-7 px-2"
                >
                  {copiedId === `structured-${activeCategory}` ? (
                    <Check className="w-3.5 h-3.5 text-green-500" />
                  ) : (
                    <Copy className="w-3.5 h-3.5" />
                  )}
                </Button>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleExportCategory}
                  className="h-7 px-2"
                >
                  <Download className="w-3.5 h-3.5" />
                </Button>
              </div>
            </div>
            <div className="px-4 py-4">
              <div className="prose dark:prose-invert prose-sm max-w-none prose-headings:text-slate-900 dark:prose-headings:text-slate-100 prose-p:text-slate-600 dark:prose-p:text-slate-300 prose-li:text-slate-600 dark:prose-li:text-slate-300 prose-strong:text-slate-900 dark:prose-strong:text-slate-100">
                <ReactMarkdown>{currentContent}</ReactMarkdown>
              </div>
            </div>
          </div>

          {/* Generation date footer */}
          {data?.fecha_generacion && (
            <p className="text-xs text-slate-400 dark:text-slate-500 text-right">
              {t('generated')}{new Date(data.fecha_generacion).toLocaleString()}
            </p>
          )}
        </div>
      )}
    </PageLayout>
  );
}

export default Resumenes;
