/**
 * Resumenes Page
 * ==============
 * Display LLM-generated summaries from analysis:
 * - Resumen Descriptivo (descriptive overview)
 * - Resumen Estructurado (structured analysis)
 * - Insights Estratégicos (strategic insights)
 *
 * Data source: insights_textuales.json (generated by Phase 8)
 */

import React, { useState, useEffect, useCallback, useMemo } from 'react';
import ReactMarkdown from 'react-markdown';
import { useTranslation } from 'react-i18next';
import {
  Lightbulb,
  RefreshCw,
  FileText,
  Target,
  Copy,
  Check,
  Download,
  Folder,
  Globe,
  Tag,
  type LucideIcon,
} from 'lucide-react';
import { PageLayout } from '../components/layout';
import { Button } from '../components/ui';
import { cn } from '../lib/utils';

/* ──────────────────── Helpers ──────────────────── */

/** Remove surrounding quotes from string values */
const cleanQuotes = (value: string | number): string | number => {
  if (typeof value === 'string') {
    return value.replace(/^["']|["']$/g, '');
  }
  return value;
};

/** Translate category names from Python to current language */
const translateCategoryName = (category: string, t: (key: string) => string): string => {
  // Remove surrounding quotes first
  const cleaned = typeof category === 'string' ? category.replace(/^["']|["']$/g, '') : String(category);
  
  // Try to translate
  const key = `common:dataLabels.categories.${cleaned}`;
  const translated = t(key);
  return translated !== key ? translated : cleaned;
};

/* ──────────────────── Types ──────────────────── */

interface ResumenesData {
  descriptivo?: {
    por_categoria?: Record<string, string>;
    global?: string;
  };
  estructurado?: {
    por_categoria?: Record<string, string>;
    global?: string;
  };
  insights?: {
    por_categoria?: Record<string, string>;
    global?: string;
  };
}

interface InsightsDataFile {
  fecha_generacion: string;
  resumenes: ResumenesData;
}

/* ──────────────────── Sub-components ──────────────────── */

type SummaryType = 'descriptivo' | 'estructurado' | 'insights';

const SUMMARY_TABS: { id: SummaryType; labelKey: string; icon: React.ComponentType<{ className?: string }> }[] = [
  { id: 'descriptivo', labelKey: 'tabs.descriptive', icon: FileText },
  { id: 'estructurado', labelKey: 'tabs.structured', icon: Target },
  { id: 'insights', labelKey: 'tabs.insights', icon: Lightbulb },
];

function SummarySection({ resumenes }: { resumenes: ResumenesData }) {
  const { t } = useTranslation(['resumenes', 'common']);
  const [activeTab, setActiveTab] = useState<SummaryType>('descriptivo');
  const [activeCategory, setActiveCategory] = useState<string>('global');
  const [copiedId, setCopiedId] = useState<string | null>(null);

  const currentSummary = resumenes[activeTab];
  const categories = useMemo(() => {
    if (!currentSummary?.por_categoria) return [];
    return Object.keys(currentSummary.por_categoria).sort();
  }, [currentSummary]);

  const currentContent = useMemo(() => {
    if (activeCategory === 'global') {
      return currentSummary?.global || t('emptyGlobal');
    }
    return currentSummary?.por_categoria?.[activeCategory] || t('emptyCategory');
  }, [currentSummary, activeCategory]);

  const handleCopy = useCallback((id: string, text: string) => {
    navigator.clipboard.writeText(text);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  }, []);

  const handleExportCategory = useCallback(async () => {
    if (!currentContent) return;

    const fileName = `resumen_${activeTab}_${activeCategory}.md`;
    const result = await window.electronAPI.files.selectDirectory();
    if (!result) return;

    try {
      const filePath = `${result}/${fileName}`;
      await window.electronAPI.files.writeFile(filePath, currentContent);
    } catch (err) {
      console.error('Failed to export:', err);
    }
  }, [activeTab, activeCategory, currentContent]);

  return (
    <div className="space-y-4">
      {/* Summary Type Tabs */}
      <div className="flex flex-wrap gap-2">
        {SUMMARY_TABS.map(({ id, labelKey, icon: Icon }) => (
          <button
            key={id}
            onClick={() => {
              setActiveTab(id);
              setActiveCategory('global');
            }}
            className={cn(
              'flex items-center gap-2 px-4 py-2 rounded-lg font-medium text-sm transition-colors cursor-pointer',
              activeTab === id
                ? 'bg-blue-600 text-white'
                : 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400 hover:bg-slate-200 dark:hover:bg-slate-700'
            )}
          >
            <Icon className="w-4 h-4" />
            {t(labelKey)}
          </button>
        ))}
      </div>

      {/* Category filters (if per_categoria exists) */}
      {categories.length > 0 && (
        <div className="flex items-center gap-2 flex-wrap">
          <button
            onClick={() => setActiveCategory('global')}
            className={cn(
              'flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-colors cursor-pointer',
              activeCategory === 'global'
                ? 'bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 border border-blue-300 dark:border-blue-700'
                : 'bg-white dark:bg-slate-800 text-slate-600 dark:text-slate-400 border border-slate-200 dark:border-slate-700 hover:border-blue-300 dark:hover:border-blue-700'
            )}
          >
            <Globe className="w-3.5 h-3.5" />
            {t('globalSummary')}
          </button>
          {categories.map((cat) => (
            <button
              key={cat}
              onClick={() => setActiveCategory(cat)}
              className={cn(
                'flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-colors cursor-pointer',
                activeCategory === cat
                  ? 'bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 border border-blue-300 dark:border-blue-700'
                  : 'bg-white dark:bg-slate-800 text-slate-600 dark:text-slate-400 border border-slate-200 dark:border-slate-700 hover:border-blue-300 dark:hover:border-blue-700'
              )}
            >
              <Tag className="w-3.5 h-3.5" />
              {translateCategoryName(cat, t)}
            </button>
          ))}
        </div>
      )}

      {/* Summary content card */}
      <div className="bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 overflow-hidden">
        <div className="px-4 py-3 border-b border-slate-200 dark:border-slate-700 flex items-center justify-between">
          <div className="flex items-center gap-2">
            {activeCategory === 'global' ? (
              <Globe className="w-4 h-4 text-blue-500" />
            ) : (
              <Tag className="w-4 h-4 text-blue-500" />
            )}
            <h3 className="text-sm font-semibold text-slate-900 dark:text-white">
              {activeCategory === 'global' ? t('globalSummary') : translateCategoryName(activeCategory, t)}
            </h3>
          </div>
          <div className="flex items-center gap-1.5">
            <Button
              variant="ghost"
              size="sm"
              onClick={() => handleCopy(`${activeTab}-${activeCategory}`, currentContent)}
              className="h-7 px-2"
            >
              {copiedId === `${activeTab}-${activeCategory}` ? (
                <Check className="w-3.5 h-3.5 text-green-500" />
              ) : (
                <Copy className="w-3.5 h-3.5" />
              )}
            </Button>
            <Button
              variant="ghost"
              size="sm"
              onClick={handleExportCategory}
              className="h-7 px-2"
            >
              <Download className="w-3.5 h-3.5" />
            </Button>
          </div>
        </div>
        <div className="px-4 py-4">
          <div className="prose dark:prose-invert prose-sm max-w-none prose-headings:text-slate-900 dark:prose-headings:text-slate-100 prose-p:text-slate-600 dark:prose-p:text-slate-300 prose-li:text-slate-600 dark:prose-li:text-slate-300 prose-strong:text-slate-900 dark:prose-strong:text-slate-100">
            <ReactMarkdown>{currentContent}</ReactMarkdown>
          </div>
        </div>
      </div>
    </div>
  );
}

/* ──────────────────── Main Page ──────────────────── */

export function Resumenes() {
  const { t } = useTranslation('resumenes');
  const [data, setData] = useState<InsightsDataFile | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [, setError] = useState<string | null>(null);

  const loadResumenes = useCallback(async () => {
    setIsLoading(true);
    setError(null);

    try {
      const pythonDataDir = await window.electronAPI.app.getPythonDataDir();
      const insightsPath = `${pythonDataDir}/visualizaciones/insights_textuales.json`;

      const result = await window.electronAPI.files.readFile(insightsPath);
      if (result.success && result.content) {
        const parsed: InsightsDataFile = JSON.parse(result.content);
        setData(parsed);
      } else {
        setData(null);
      }
    } catch (err) {
      console.error('[Resumenes] Failed to load:', err);
      setData(null);
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    loadResumenes();
  }, [loadResumenes]);

  const handleExportAll = async () => {
    if (!data) return;

    const result = await window.electronAPI.files.selectDirectory();
    if (!result) return;

    try {
      // Export all summaries to files
      for (const summaryType of ['descriptivo', 'estructurado', 'insights'] as SummaryType[]) {
        const summary = data.resumenes[summaryType];
        if (!summary) continue;

        // Export global
        if (summary.global) {
          const fileName = `resumen_${summaryType}_global.md`;
          const filePath = `${result}/${fileName}`;
          await window.electronAPI.files.writeFile(filePath, summary.global);
        }

        // Export per category
        if (summary.por_categoria) {
          for (const [category, content] of Object.entries(summary.por_categoria)) {
            const fileName = `resumen_${summaryType}_${category}.md`;
            const filePath = `${result}/${fileName}`;
            await window.electronAPI.files.writeFile(filePath, content);
          }
        }
      }
    } catch (err) {
      console.error('Failed to export all:', err);
    }
  };

  return (
    <PageLayout
      title={t('title')}
      description={t('description')}
      headerActions={
        <div className="flex items-center gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={loadResumenes}
            disabled={isLoading}
          >
            <RefreshCw className={cn('w-4 h-4 mr-2', isLoading && 'animate-spin')} />
            {t('actions.reload')}
          </Button>
          {data && (
            <Button
              variant="outline"
              size="sm"
              onClick={handleExportAll}
            >
              <Folder className="w-4 h-4 mr-2" />
              {t('actions.exportAll')}
            </Button>
          )}
        </div>
      }
    >
      {isLoading ? (
        <div className="flex items-center justify-center h-64">
          <RefreshCw className="w-8 h-8 animate-spin text-slate-400" />
        </div>
      ) : !data ? (
        <div className="flex flex-col items-center justify-center h-64 bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700">
          <FileText className="w-16 h-16 text-slate-300 dark:text-slate-600 mb-4" />
          <h3 className="text-lg font-medium text-slate-700 dark:text-slate-300 mb-2">
            {t('empty.title')}
          </h3>
          <p className="text-slate-500 dark:text-slate-400 text-center max-w-md">
            {t('empty.description')}
          </p>
        </div>
      ) : (
        <div className="space-y-6">
          <SummarySection resumenes={data.resumenes} />
          
          {/* Generation date footer */}
          <p className="text-xs text-slate-400 dark:text-slate-500 text-right">
            {t('generated')}{new Date(data.fecha_generacion).toLocaleString()}
          </p>
        </div>
      )}
    </PageLayout>
  );
}

export default Resumenes;
